/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from '../../../../core';
export const CreateCommunityResponseCommunityCommunityTagsItemTag =
  core.serialization.object({
    id: core.serialization.number().optional(),
    name: core.serialization.string(),
  });
