/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from '../../../../core';
import { UpdateGroupResponseRequirementsItemAllowData } from './UpdateGroupResponseRequirementsItemAllowData';
export const UpdateGroupResponseRequirementsItemAllow =
  core.serialization.object({
    data: UpdateGroupResponseRequirementsItemAllowData,
  });
