/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface GuildBank1Interface extends Interface {
  functions: {
    approvedToken: TypedFunctionDescription<{ encode([]: []): string }>;

    isOwner: TypedFunctionDescription<{ encode([]: []): string }>;

    owner: TypedFunctionDescription<{ encode([]: []): string }>;

    renounceOwnership: TypedFunctionDescription<{ encode([]: []): string }>;

    transferOwnership: TypedFunctionDescription<{
      encode([newOwner]: [string]): string;
    }>;

    withdraw: TypedFunctionDescription<{
      encode([receiver, shares, totalShares]: [
        string,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;
  };

  events: {
    OwnershipTransferred: TypedEventDescription<{
      encodeTopics([previousOwner, newOwner]: [
        string | null,
        string | null
      ]): string[];
    }>;

    Withdrawal: TypedEventDescription<{
      encodeTopics([receiver, amount]: [string | null, null]): string[];
    }>;
  };
}

export class GuildBank1 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): GuildBank1;
  attach(addressOrName: string): GuildBank1;
  deployed(): Promise<GuildBank1>;

  on(event: EventFilter | string, listener: Listener): GuildBank1;
  once(event: EventFilter | string, listener: Listener): GuildBank1;
  addListener(eventName: EventFilter | string, listener: Listener): GuildBank1;
  removeAllListeners(eventName: EventFilter | string): GuildBank1;
  removeListener(eventName: any, listener: Listener): GuildBank1;

  interface: GuildBank1Interface;

  functions: {
    approvedToken(): Promise<string>;

    /**
     * Returns true if the caller is the current owner.
     */
    isOwner(): Promise<boolean>;

    /**
     * Returns the address of the current owner.
     */
    owner(): Promise<string>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner.     * NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(
      newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    withdraw(
      receiver: string,
      shares: BigNumberish,
      totalShares: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  approvedToken(): Promise<string>;

  /**
   * Returns true if the caller is the current owner.
   */
  isOwner(): Promise<boolean>;

  /**
   * Returns the address of the current owner.
   */
  owner(): Promise<string>;

  /**
   * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner.     * NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
   */
  renounceOwnership(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  /**
   * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
   */
  transferOwnership(
    newOwner: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  withdraw(
    receiver: string,
    shares: BigNumberish,
    totalShares: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    Withdrawal(receiver: string | null, amount: null): EventFilter;
  };

  estimate: {
    approvedToken(): Promise<BigNumber>;

    isOwner(): Promise<BigNumber>;

    owner(): Promise<BigNumber>;

    renounceOwnership(): Promise<BigNumber>;

    transferOwnership(newOwner: string): Promise<BigNumber>;

    withdraw(
      receiver: string,
      shares: BigNumberish,
      totalShares: BigNumberish
    ): Promise<BigNumber>;
  };
}
