# Use a Node.js base image with version 14.x
FROM node:18.14.1-alpine

WORKDIR /app

COPY package*.json ./

RUN apk add --update python3 make g++ && rm -rf /var/cache/apk/*

RUN npm install --no-optional

COPY . .

ENV RPC_HOST=ganache
ENV CHAIN_PORT=3000

EXPOSE 3000

CMD npm start