/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __awaiter =
  (this && this.__awaiter) ||
  function (thisArg, _arguments, P, generator) {
    function adopt(value) {
      return value instanceof P
        ? value
        : new P(function (resolve) {
            resolve(value);
          });
    }
    return new (P || (P = Promise))(function (resolve, reject) {
      function fulfilled(value) {
        try {
          step(generator.next(value));
        } catch (e) {
          reject(e);
        }
      }
      function rejected(value) {
        try {
          step(generator['throw'](value));
        } catch (e) {
          reject(e);
        }
      }
      function step(result) {
        result.done
          ? resolve(result.value)
          : adopt(result.value).then(fulfilled, rejected);
      }
      step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
  };
import urlJoin from 'url-join';
import * as core from '../../../../core';
import * as environments from '../../../../environments';
import * as errors from '../../../../errors/index';
import * as serializers from '../../../../serialization/index';
export class User {
  constructor(_options) {
    this._options = _options;
  }
  /**
   * @param {CommonApi.GetUserActivityRequest} request
   * @param {User.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @example
   *     await client.user.getUserActivity()
   */
  getUserActivity(request = {}, requestOptions) {
    var _a;
    return __awaiter(this, void 0, void 0, function* () {
      const { isGlobal, threadLimit, commentLimit } = request;
      const _queryParams = {};
      if (isGlobal != null) {
        _queryParams['is_global'] = isGlobal.toString();
      }
      if (threadLimit != null) {
        _queryParams['thread_limit'] = threadLimit.toString();
      }
      if (commentLimit != null) {
        _queryParams['comment_limit'] = commentLimit.toString();
      }
      const _response = yield core.fetcher({
        url: urlJoin(
          (_a = yield core.Supplier.get(this._options.environment)) !== null &&
            _a !== void 0
            ? _a
            : environments.CommonApiEnvironment.Default,
          'GetUserActivity',
        ),
        method: 'GET',
        headers: Object.assign(
          {
            address:
              (yield core.Supplier.get(this._options.address)) != null
                ? yield core.Supplier.get(this._options.address)
                : undefined,
            'X-Fern-Language': 'JavaScript',
            'X-Fern-Runtime': core.RUNTIME.type,
            'X-Fern-Runtime-Version': core.RUNTIME.version,
          },
          yield this._getCustomAuthorizationHeaders(),
        ),
        contentType: 'application/json',
        queryParameters: _queryParams,
        requestType: 'json',
        timeoutMs:
          (requestOptions === null || requestOptions === void 0
            ? void 0
            : requestOptions.timeoutInSeconds) != null
            ? requestOptions.timeoutInSeconds * 1000
            : 60000,
        maxRetries:
          requestOptions === null || requestOptions === void 0
            ? void 0
            : requestOptions.maxRetries,
        abortSignal:
          requestOptions === null || requestOptions === void 0
            ? void 0
            : requestOptions.abortSignal,
      });
      if (_response.ok) {
        return serializers.user.getUserActivity.Response.parseOrThrow(
          _response.body,
          {
            unrecognizedObjectKeys: 'passthrough',
            allowUnrecognizedUnionMembers: true,
            allowUnrecognizedEnumValues: true,
            breadcrumbsPrefix: ['response'],
          },
        );
      }
      if (_response.error.reason === 'status-code') {
        throw new errors.CommonApiError({
          statusCode: _response.error.statusCode,
          body: _response.error.body,
        });
      }
      switch (_response.error.reason) {
        case 'non-json':
          throw new errors.CommonApiError({
            statusCode: _response.error.statusCode,
            body: _response.error.rawBody,
          });
        case 'timeout':
          throw new errors.CommonApiTimeoutError();
        case 'unknown':
          throw new errors.CommonApiError({
            message: _response.error.errorMessage,
          });
      }
    });
  }
  /**
   * @param {User.RequestOptions} requestOptions - Request-specific configuration.
   *
   * @example
   *     await client.user.getNewContent()
   */
  getNewContent(requestOptions) {
    var _a;
    return __awaiter(this, void 0, void 0, function* () {
      const _response = yield core.fetcher({
        url: urlJoin(
          (_a = yield core.Supplier.get(this._options.environment)) !== null &&
            _a !== void 0
            ? _a
            : environments.CommonApiEnvironment.Default,
          'GetNewContent',
        ),
        method: 'GET',
        headers: Object.assign(
          {
            address:
              (yield core.Supplier.get(this._options.address)) != null
                ? yield core.Supplier.get(this._options.address)
                : undefined,
            'X-Fern-Language': 'JavaScript',
            'X-Fern-Runtime': core.RUNTIME.type,
            'X-Fern-Runtime-Version': core.RUNTIME.version,
          },
          yield this._getCustomAuthorizationHeaders(),
        ),
        contentType: 'application/json',
        requestType: 'json',
        timeoutMs:
          (requestOptions === null || requestOptions === void 0
            ? void 0
            : requestOptions.timeoutInSeconds) != null
            ? requestOptions.timeoutInSeconds * 1000
            : 60000,
        maxRetries:
          requestOptions === null || requestOptions === void 0
            ? void 0
            : requestOptions.maxRetries,
        abortSignal:
          requestOptions === null || requestOptions === void 0
            ? void 0
            : requestOptions.abortSignal,
      });
      if (_response.ok) {
        return serializers.GetNewContentResponse.parseOrThrow(_response.body, {
          unrecognizedObjectKeys: 'passthrough',
          allowUnrecognizedUnionMembers: true,
          allowUnrecognizedEnumValues: true,
          breadcrumbsPrefix: ['response'],
        });
      }
      if (_response.error.reason === 'status-code') {
        throw new errors.CommonApiError({
          statusCode: _response.error.statusCode,
          body: _response.error.body,
        });
      }
      switch (_response.error.reason) {
        case 'non-json':
          throw new errors.CommonApiError({
            statusCode: _response.error.statusCode,
            body: _response.error.rawBody,
          });
        case 'timeout':
          throw new errors.CommonApiTimeoutError();
        case 'unknown':
          throw new errors.CommonApiError({
            message: _response.error.errorMessage,
          });
      }
    });
  }
  _getCustomAuthorizationHeaders() {
    return __awaiter(this, void 0, void 0, function* () {
      const apiKeyValue = yield core.Supplier.get(this._options.apiKey);
      return { 'x-api-key': apiKeyValue };
    });
  }
}
