resources:
  - ../../base

patches:
  - target:
      kind: ApplicationSet
      name: preview-services
    patch: |-
      - op: replace
        path: /spec/template/metadata/name
        value: "development-preview-{{.branch}}-{{.number}}"
      - op: replace
        path: /spec/template/spec/sources/0/helm/values
        value: |
          auth:
            username: pr-{{.number}}
            password: "test"
          namespace: development-preview-{{.branch}}-{{.number}}
      - op: replace
        path: /spec/template/spec/sources/1/helm/values
        value: |
          auth:
            password: "test"
          namespace: development-preview-{{.branch}}-{{.number}}
      - op: replace
        path: /spec/template/spec/destination/namespace
        value: "development-preview-{{.branch}}-{{.number}}"
