/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IProjectBaseInterface extends ethers.utils.Interface {
  functions: {
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    "acceptedToken()": FunctionFragment;
    "back(uint256)": FunctionFragment;
    "backersWithdraw()": FunctionFragment;
    "beneficiary()": FunctionFragment;
    "beneficiaryWithdraw()": FunctionFragment;
    "deadline()": FunctionFragment;
    "funded()": FunctionFragment;
    "lockedWithdraw()": FunctionFragment;
    "metaData()": FunctionFragment;
    "protocolFee()": FunctionFragment;
    "protocolFeeTo()": FunctionFragment;
    "setIpfsHash(bytes32)": FunctionFragment;
    "setName(bytes32)": FunctionFragment;
    "threshold()": FunctionFragment;
    "totalFunding()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptedToken",
    values?: undefined
  ): string;
=======
    "back(uint256)": FunctionFragment;
    "backersWithdraw()": FunctionFragment;
    "beneficiaryWithdraw()": FunctionFragment;
    "funded()": FunctionFragment;
    "lockedWithdraw()": FunctionFragment;
    "metaData()": FunctionFragment;
    "projectData()": FunctionFragment;
    "protocolData()": FunctionFragment;
    "setIpfsHash(bytes32)": FunctionFragment;
    "setName(bytes32)": FunctionFragment;
    "setUrl(bytes32)": FunctionFragment;
    "totalFunding()": FunctionFragment;
  };

>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
  encodeFunctionData(functionFragment: "back", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "backersWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    functionFragment: "beneficiary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "beneficiaryWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deadline", values?: undefined): string;
=======
    functionFragment: "beneficiaryWithdraw",
    values?: undefined
  ): string;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
  encodeFunctionData(functionFragment: "funded", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lockedWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "metaData", values?: undefined): string;
  encodeFunctionData(
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    functionFragment: "protocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeeTo",
=======
    functionFragment: "projectData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolData",
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setIpfsHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "setName", values: [BytesLike]): string;
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
  encodeFunctionData(functionFragment: "threshold", values?: undefined): string;
=======
  encodeFunctionData(functionFragment: "setUrl", values: [BytesLike]): string;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
  encodeFunctionData(
    functionFragment: "totalFunding",
    values?: undefined
  ): string;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
  decodeFunctionResult(
    functionFragment: "acceptedToken",
    data: BytesLike
  ): Result;
=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
  decodeFunctionResult(functionFragment: "back", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "backersWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    functionFragment: "beneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beneficiaryWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deadline", data: BytesLike): Result;
=======
    functionFragment: "beneficiaryWithdraw",
    data: BytesLike
  ): Result;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
  decodeFunctionResult(functionFragment: "funded", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockedWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "metaData", data: BytesLike): Result;
  decodeFunctionResult(
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    functionFragment: "protocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeTo",
=======
    functionFragment: "projectData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolData",
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIpfsHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setName", data: BytesLike): Result;
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
  decodeFunctionResult(functionFragment: "threshold", data: BytesLike): Result;
=======
  decodeFunctionResult(functionFragment: "setUrl", data: BytesLike): Result;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
  decodeFunctionResult(
    functionFragment: "totalFunding",
    data: BytesLike
  ): Result;

  events: {
    "Back(address,address,uint256)": EventFragment;
    "Failed()": EventFragment;
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
=======
    "ProjectDataChange(bytes32,bytes32,bytes32)": EventFragment;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    "Succeeded(uint256,uint256)": EventFragment;
    "Withdraw(address,address,uint256,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Back"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Failed"): EventFragment;
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
=======
  getEvent(nameOrSignatureOrTopic: "ProjectDataChange"): EventFragment;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
  getEvent(nameOrSignatureOrTopic: "Succeeded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export class IProjectBase extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IProjectBaseInterface;

  functions: {
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    acceptedToken(overrides?: CallOverrides): Promise<[string]>;

    "acceptedToken()"(overrides?: CallOverrides): Promise<[string]>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    back(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "back(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    backersWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "backersWithdraw()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    beneficiary(overrides?: CallOverrides): Promise<[string]>;

    "beneficiary()"(overrides?: CallOverrides): Promise<[string]>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    beneficiaryWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "beneficiaryWithdraw()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    deadline(overrides?: CallOverrides): Promise<[BigNumber]>;

    "deadline()"(overrides?: CallOverrides): Promise<[BigNumber]>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    funded(overrides?: CallOverrides): Promise<[boolean]>;

    "funded()"(overrides?: CallOverrides): Promise<[boolean]>;

    lockedWithdraw(overrides?: CallOverrides): Promise<[boolean]>;

    "lockedWithdraw()"(overrides?: CallOverrides): Promise<[boolean]>;

    metaData(
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, string, string, string, string] & {
          id: BigNumber;
          name: string;
          ipfsHash: string;
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
          cwUrl: string;
=======
          url: string;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
          creator: string;
        }
      ]
    >;

    "metaData()"(
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, string, string, string, string] & {
          id: BigNumber;
          name: string;
          ipfsHash: string;
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
          cwUrl: string;
=======
          url: string;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
          creator: string;
        }
      ]
    >;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    protocolFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    "protocolFee()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    protocolFeeTo(overrides?: CallOverrides): Promise<[string]>;

    "protocolFeeTo()"(overrides?: CallOverrides): Promise<[string]>;
=======
    projectData(
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, string, string] & {
          threshold: BigNumber;
          deadline: BigNumber;
          beneficiary: string;
          acceptedToken: string;
        }
      ]
    >;

    "projectData()"(
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, string, string] & {
          threshold: BigNumber;
          deadline: BigNumber;
          beneficiary: string;
          acceptedToken: string;
        }
      ]
    >;

    protocolData(
      overrides?: CallOverrides
    ): Promise<[[number, string] & { fee: number; feeTo: string }]>;

    "protocolData()"(
      overrides?: CallOverrides
    ): Promise<[[number, string] & { fee: number; feeTo: string }]>;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts

    setIpfsHash(
      _ipfsHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setIpfsHash(bytes32)"(
      _ipfsHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setName(
      _name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setName(bytes32)"(
      _name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    threshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    "threshold()"(overrides?: CallOverrides): Promise<[BigNumber]>;
=======
    setUrl(
      _url: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setUrl(bytes32)"(
      _url: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts

    totalFunding(overrides?: CallOverrides): Promise<[BigNumber]>;

    "totalFunding()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
  acceptedToken(overrides?: CallOverrides): Promise<string>;

  "acceptedToken()"(overrides?: CallOverrides): Promise<string>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
  back(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "back(uint256)"(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  backersWithdraw(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "backersWithdraw()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
  beneficiary(overrides?: CallOverrides): Promise<string>;

  "beneficiary()"(overrides?: CallOverrides): Promise<string>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
  beneficiaryWithdraw(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "beneficiaryWithdraw()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
  deadline(overrides?: CallOverrides): Promise<BigNumber>;

  "deadline()"(overrides?: CallOverrides): Promise<BigNumber>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
  funded(overrides?: CallOverrides): Promise<boolean>;

  "funded()"(overrides?: CallOverrides): Promise<boolean>;

  lockedWithdraw(overrides?: CallOverrides): Promise<boolean>;

  "lockedWithdraw()"(overrides?: CallOverrides): Promise<boolean>;

  metaData(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, string, string] & {
      id: BigNumber;
      name: string;
      ipfsHash: string;
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
      cwUrl: string;
=======
      url: string;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
      creator: string;
    }
  >;

  "metaData()"(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, string, string] & {
      id: BigNumber;
      name: string;
      ipfsHash: string;
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
      cwUrl: string;
=======
      url: string;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
      creator: string;
    }
  >;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
  protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

  "protocolFee()"(overrides?: CallOverrides): Promise<BigNumber>;

  protocolFeeTo(overrides?: CallOverrides): Promise<string>;

  "protocolFeeTo()"(overrides?: CallOverrides): Promise<string>;
=======
  projectData(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, string, string] & {
      threshold: BigNumber;
      deadline: BigNumber;
      beneficiary: string;
      acceptedToken: string;
    }
  >;

  "projectData()"(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, string, string] & {
      threshold: BigNumber;
      deadline: BigNumber;
      beneficiary: string;
      acceptedToken: string;
    }
  >;

  protocolData(
    overrides?: CallOverrides
  ): Promise<[number, string] & { fee: number; feeTo: string }>;

  "protocolData()"(
    overrides?: CallOverrides
  ): Promise<[number, string] & { fee: number; feeTo: string }>;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts

  setIpfsHash(
    _ipfsHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setIpfsHash(bytes32)"(
    _ipfsHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setName(
    _name: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setName(bytes32)"(
    _name: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
  threshold(overrides?: CallOverrides): Promise<BigNumber>;

  "threshold()"(overrides?: CallOverrides): Promise<BigNumber>;
=======
  setUrl(
    _url: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setUrl(bytes32)"(
    _url: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts

  totalFunding(overrides?: CallOverrides): Promise<BigNumber>;

  "totalFunding()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    acceptedToken(overrides?: CallOverrides): Promise<string>;

    "acceptedToken()"(overrides?: CallOverrides): Promise<string>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    back(_amount: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    "back(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    backersWithdraw(overrides?: CallOverrides): Promise<boolean>;

    "backersWithdraw()"(overrides?: CallOverrides): Promise<boolean>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    beneficiary(overrides?: CallOverrides): Promise<string>;

    "beneficiary()"(overrides?: CallOverrides): Promise<string>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    beneficiaryWithdraw(overrides?: CallOverrides): Promise<boolean>;

    "beneficiaryWithdraw()"(overrides?: CallOverrides): Promise<boolean>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    deadline(overrides?: CallOverrides): Promise<BigNumber>;

    "deadline()"(overrides?: CallOverrides): Promise<BigNumber>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    funded(overrides?: CallOverrides): Promise<boolean>;

    "funded()"(overrides?: CallOverrides): Promise<boolean>;

    lockedWithdraw(overrides?: CallOverrides): Promise<boolean>;

    "lockedWithdraw()"(overrides?: CallOverrides): Promise<boolean>;

    metaData(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, string, string] & {
        id: BigNumber;
        name: string;
        ipfsHash: string;
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
        cwUrl: string;
=======
        url: string;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
        creator: string;
      }
    >;

    "metaData()"(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, string, string] & {
        id: BigNumber;
        name: string;
        ipfsHash: string;
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
        cwUrl: string;
=======
        url: string;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
        creator: string;
      }
    >;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    "protocolFee()"(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeTo(overrides?: CallOverrides): Promise<string>;

    "protocolFeeTo()"(overrides?: CallOverrides): Promise<string>;
=======
    projectData(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string, string] & {
        threshold: BigNumber;
        deadline: BigNumber;
        beneficiary: string;
        acceptedToken: string;
      }
    >;

    "projectData()"(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string, string] & {
        threshold: BigNumber;
        deadline: BigNumber;
        beneficiary: string;
        acceptedToken: string;
      }
    >;

    protocolData(
      overrides?: CallOverrides
    ): Promise<[number, string] & { fee: number; feeTo: string }>;

    "protocolData()"(
      overrides?: CallOverrides
    ): Promise<[number, string] & { fee: number; feeTo: string }>;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts

    setIpfsHash(_ipfsHash: BytesLike, overrides?: CallOverrides): Promise<void>;

    "setIpfsHash(bytes32)"(
      _ipfsHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setName(_name: BytesLike, overrides?: CallOverrides): Promise<void>;

    "setName(bytes32)"(
      _name: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    threshold(overrides?: CallOverrides): Promise<BigNumber>;

    "threshold()"(overrides?: CallOverrides): Promise<BigNumber>;
=======
    setUrl(_url: BytesLike, overrides?: CallOverrides): Promise<void>;

    "setUrl(bytes32)"(
      _url: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts

    totalFunding(overrides?: CallOverrides): Promise<BigNumber>;

    "totalFunding()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    Back(
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
      sender: null,
      token: null,
=======
      sender: string | null,
      token: string | null,
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
      amount: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { sender: string; token: string; amount: BigNumber }
    >;

    Failed(): TypedEventFilter<[], {}>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
=======
    ProjectDataChange(
      name: null,
      oldData: null,
      newData: null
    ): TypedEventFilter<
      [string, string, string],
      { name: string; oldData: string; newData: string }
    >;

>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    Succeeded(
      timestamp: null,
      amount: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { timestamp: BigNumber; amount: BigNumber }
    >;

    Withdraw(
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
      sender: null,
      token: null,
=======
      sender: string | null,
      token: string | null,
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
      amount: null,
      withdrawalType: null
    ): TypedEventFilter<
      [string, string, BigNumber, string],
      {
        sender: string;
        token: string;
        amount: BigNumber;
        withdrawalType: string;
      }
    >;
  };

  estimateGas: {
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    acceptedToken(overrides?: CallOverrides): Promise<BigNumber>;

    "acceptedToken()"(overrides?: CallOverrides): Promise<BigNumber>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    back(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "back(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    backersWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "backersWithdraw()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    beneficiary(overrides?: CallOverrides): Promise<BigNumber>;

    "beneficiary()"(overrides?: CallOverrides): Promise<BigNumber>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    beneficiaryWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "beneficiaryWithdraw()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    deadline(overrides?: CallOverrides): Promise<BigNumber>;

    "deadline()"(overrides?: CallOverrides): Promise<BigNumber>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    funded(overrides?: CallOverrides): Promise<BigNumber>;

    "funded()"(overrides?: CallOverrides): Promise<BigNumber>;

    lockedWithdraw(overrides?: CallOverrides): Promise<BigNumber>;

    "lockedWithdraw()"(overrides?: CallOverrides): Promise<BigNumber>;

    metaData(overrides?: CallOverrides): Promise<BigNumber>;

    "metaData()"(overrides?: CallOverrides): Promise<BigNumber>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    "protocolFee()"(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeTo(overrides?: CallOverrides): Promise<BigNumber>;

    "protocolFeeTo()"(overrides?: CallOverrides): Promise<BigNumber>;
=======
    projectData(overrides?: CallOverrides): Promise<BigNumber>;

    "projectData()"(overrides?: CallOverrides): Promise<BigNumber>;

    protocolData(overrides?: CallOverrides): Promise<BigNumber>;

    "protocolData()"(overrides?: CallOverrides): Promise<BigNumber>;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts

    setIpfsHash(
      _ipfsHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setIpfsHash(bytes32)"(
      _ipfsHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setName(
      _name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setName(bytes32)"(
      _name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    threshold(overrides?: CallOverrides): Promise<BigNumber>;

    "threshold()"(overrides?: CallOverrides): Promise<BigNumber>;
=======
    setUrl(
      _url: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setUrl(bytes32)"(
      _url: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts

    totalFunding(overrides?: CallOverrides): Promise<BigNumber>;

    "totalFunding()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    acceptedToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "acceptedToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    back(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "back(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    backersWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "backersWithdraw()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    beneficiary(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "beneficiary()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    beneficiaryWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "beneficiaryWithdraw()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    deadline(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "deadline()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

=======
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts
    funded(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "funded()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lockedWithdraw(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "lockedWithdraw()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    metaData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "metaData()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    protocolFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "protocolFee()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFeeTo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "protocolFeeTo()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
=======
    projectData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "projectData()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "protocolData()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts

    setIpfsHash(
      _ipfsHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setIpfsHash(bytes32)"(
      _ipfsHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setName(
      _name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setName(bytes32)"(
      _name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

<<<<<<< HEAD:shared/eth/types/IProjectBase.d.ts
    threshold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "threshold()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
=======
    setUrl(
      _url: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setUrl(bytes32)"(
      _url: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
>>>>>>> master:packages/chain-events/src/contractTypes/IProjectBase.d.ts

    totalFunding(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalFunding()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
