services:
  cw_postgres:
    container_name: cw_postgres
    build:
      context: ./packages/commonwealth/docker/
      dockerfile: Dockerfile-pg-partman
    restart: always
    environment:
      POSTGRES_USER: commonwealth
      POSTGRES_PASSWORD: edgeware
      POSTGRES_DB: commonwealth
    volumes:
      - .postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U commonwealth']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    networks:
      - cw-network

  cw_rabbitmq:
    container_name: cw_rabbitmq
    image: rabbitmq:3.11-management
    restart: always
    # environment:
    #   RABBITMQ_DEFAULT_USER: commonwealth
    #   RABBITMQ_DEFAULT_PASS: edgeware
    volumes:
      - '.rabbitmq:/var/lib/rabbitmq/mnesia/'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - cw-network

  local-redis:
    container_name: local-redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    networks:
      - cw-network

  commonwealth:
    profiles:
      - with-app
    container_name: commonwealth
    build:
      context: .
      dockerfile: ./Dockerfile.web
    ports:
      - '8080:8080'
    environment:
      APP_ENV: local
      SERVER_URL: http://localhost:8080
      AWS_REGION: us-east-1
      COSMOS_GOV_V1: kyve,csdk,csdk-v1,quicksilver-protocol,juno,regen
      COSMOS_REGISTRY_API: https://cosmoschains.thesilverfox.pro
      DATABASE_URL: postgresql://commonwealth:edgeware@cw_postgres/commonwealth
      MAGIC_DEFAULT_CHAIN: ethereum
      MAGIC_SUPPORTED_BASES: cosmos,ethereum
      NODE_ENV: development
      PGPASSWORD: edgeware
      PORT: 8080
      REDIS_URL: redis://local-redis:6379
      SL_PORT: 8001
    networks:
      - cw-network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl --silent --fail http://localhost:8080/api/health || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - cw_postgres
      - cw_rabbitmq
      - local-redis

networks:
  cw-network:
    name: cw-network
