export const codeBlockLanguages: { [key: string]: string } = {
  // apl: "APL",
  // asciiarmor: "PGP",
  // "asn.1": "ASN.1",
  // asterisk: "Asterisk",
  // brainfuck: "Brainfuck",
  // clike: "C/C++/Java/Scala",
  // ceylon: "Ceylon",
  clojure: 'Clojure',
  // cmake: "CMake",
  cobol: 'Cobol',
  // coffeescript: "CoffeeScript",
  // commonlisp: "Common Lisp",
  // crystal: "Crystal",
  // css: "CSS",
  // cython: "Cython",
  // d: "D",
  // dart: "Dart",
  // diff: "Diff",
  // django: "Django",
  dockerfile: 'Dockerfile',
  // dtd: "DTD",
  // dylan: "Dylan",
  // ebnf: "EBNF",
  // ecl: "ECL",
  // eiffel: "Eiffel",
  // elm: "Elm",
  erlang: 'Erlang',
  // factor: "Factor",
  // fcl: "FCL",
  // forth: "Forth",
  // fortran: "Fortran",
  // gas: "Gas (Assembly)",
  // gherkin: "Gherkin",
  go: 'Go',
  // groovy: "Groovy",
  // haml: "HAML",
  haskell: 'Haskell',
  // haxe: "Haxe",
  // htmlmixed: "HTML",
  // http: "HTTP",
  idl: 'IDL',
  // pug: "Jade/Pug",
  js: 'JavaScript',
  // jinja2: "Jinja2",
  // julia: "Julia",
  // kotlin: "Kotlin",
  // stex: "LaTeX",
  // less: "LESS",
  // livescript: "LiveScript",
  // lua: "Lua",
  markdown: 'Markdown',
  // mathematica: "Mathematica",
  // octave: "MATLAB/Octave",
  // mercury: "Mercury",
  // mirah: "MIRAH",
  // nginx: "Nginx",
  // nsis: "NSIS",
  // ntriples: "NTriples",
  // mllike: "OCaml",
  pascal: 'Pascal',
  // pegjs: "PEG.js",
  perl: 'Perl',
  php: 'PHP',
  // pig: "Pig Latin",
  // powershell: "PowerShell",
  // properties: "Properties (INI)",
  // protobuf: "Protobuf",
  python: 'Python',
  // q: "Q",
  // r: "R",
  // rst: "reStructuredText",
  ruby: 'Ruby',
  rust: 'Rust',
  // sas: "SAS",
  sass: 'Sass',
  // scheme: "Scheme",
  // scss: "SCSS",
  shell: 'Shell',
  // sieve: "Sieve",
  // slim: "Slim",
  // smalltalk: "Smalltalk",
  // smarty: "Smarty",
  // solr: "Solr",
  // soy: "Soy",
  // sparql: "SPARQL",
  // spreadsheet: "Spreadsheet (Excel)",
  sql: 'SQL',
  // squirrel: "Squirrel",
  // stylus: "Stylus",
  // swift: "Swift",
  // tcl: "Tcl",
  // textile: "Textile",
  // toml: "TOML",
  // turtle: "Turtle",
  // twig: "Twig",
  // vb: "VB.NET",
  // velocity: "Velocity",
  // verilog: "Verilog",
  // vhdl: "VHDL",
  // vue: "Vue.js",
  // wast: "WebAssembly",
  xml: 'XML',
  // xquery: "XQuery",
  yaml: 'YAML',
  // z80: "Z80 (Assembly)"
};
