/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from "../../../index";
export interface UpdateThreadResponseCollaboratorsItem {
    id?: number;
    address: string;
    communityId: string;
    userId?: number;
    verificationToken?: string;
    verificationTokenExpires?: Date;
    verified?: Date;
    lastActive?: Date;
    ghostAddress?: boolean;
    walletId?: CommonApi.UpdateThreadResponseCollaboratorsItemWalletId;
    blockInfo?: string;
    isUserDefault?: boolean;
    role?: CommonApi.UpdateThreadResponseCollaboratorsItemRole;
    isBanned?: boolean;
    hex?: string;
    user?: CommonApi.UpdateThreadResponseCollaboratorsItemUser;
    createdAt?: Date;
    updatedAt?: Date;
}
