export const communityStakesAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_feeDestination', type: 'address', internalType: 'address' },
      {
        name: '_factory',
        type: 'address',
        internalType: 'address',
      },
      { name: '_protocolFee', type: 'uint256', internalType: 'uint256' },
      {
        name: '_namespaceFee',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: '_curveManager', type: 'address', internalType: 'address' },
      {
        name: '_supplyCap',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: '_supplyCapGuardian', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    name: 'AddressEmptyCode',
    type: 'error',
    inputs: [{ name: 'target', type: 'address', internalType: 'address' }],
  },
  {
    name: 'AddressInsufficientBalance',
    type: 'error',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  { name: 'FailedInnerCall', type: 'error', inputs: [] },
  {
    name: 'OwnableInvalidOwner',
    type: 'error',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
  },
  {
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  {
    name: 'SafeERC20FailedOperation',
    type: 'error',
    inputs: [{ name: 'token', type: 'address', internalType: 'address' }],
  },
  {
    name: 'OwnershipTransferred',
    type: 'event',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    name: 'Trade',
    type: 'event',
    inputs: [
      {
        name: 'trader',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'namespace',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'isBuy',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: 'communityTokenAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'ethAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'protocolEthAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'nameSpaceEthAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'supply',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'exchangeToken',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    name: 'blacklistTokens',
    type: 'function',
    inputs: [{ name: 'tokens', type: 'address[]', internalType: 'address[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'bondingCurveAddress',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'buyStake',
    type: 'function',
    inputs: [
      { name: 'namespaceAddress', type: 'address', internalType: 'address' },
      {
        name: 'id',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'payable',
  },
  {
    name: 'curveId',
    type: 'function',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'factory',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'getBuyPrice',
    type: 'function',
    inputs: [
      { name: 'namespaceAddress', type: 'address', internalType: 'address' },
      {
        name: 'id',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'getBuyPriceAfterFee',
    type: 'function',
    inputs: [
      { name: 'namespaceAddress', type: 'address', internalType: 'address' },
      {
        name: 'id',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'getDecimals',
    type: 'function',
    inputs: [
      { name: 'namespaceAddress', type: 'address', internalType: 'address' },
      {
        name: 'id',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [{ name: '', type: 'uint8', internalType: 'uint8' }],
    stateMutability: 'view',
  },
  {
    name: 'getPrice',
    type: 'function',
    inputs: [
      { name: '_supply', type: 'uint256', internalType: 'uint256' },
      {
        name: 'namespaceAddress',
        type: 'address',
        internalType: 'address',
      },
      { name: 'id', type: 'uint256', internalType: 'uint256' },
      {
        name: 'amount',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'getSellPrice',
    type: 'function',
    inputs: [
      { name: 'namespaceAddress', type: 'address', internalType: 'address' },
      {
        name: 'id',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'getSellPriceAfterFee',
    type: 'function',
    inputs: [
      { name: 'namespaceAddress', type: 'address', internalType: 'address' },
      {
        name: 'id',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'namespaceFeePercent',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'owner',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'protocolFeeDestination',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'protocolFeePercent',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'renounceOwnership',
    type: 'function',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'sellStake',
    type: 'function',
    inputs: [
      { name: 'namespaceAddress', type: 'address', internalType: 'address' },
      {
        name: 'id',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    name: 'setBondingCurveAddress',
    type: 'function',
    inputs: [
      {
        name: '_bondingCurveAddress',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setFactory',
    type: 'function',
    inputs: [{ name: '_factory', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setFeeDestination',
    type: 'function',
    inputs: [
      { name: '_feeDestination', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'supplyCapGuardian',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'tokenBlacklist',
    type: 'function',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'totalSupply',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'totalSupplyCap',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'transferGuardian',
    type: 'function',
    inputs: [{ name: 'newGuardian', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'transferOwnership',
    type: 'function',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'updateSupplyCap',
    type: 'function',
    inputs: [{ name: 'newCap', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'whitelist',
    type: 'function',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'whitelistId',
    type: 'function',
    inputs: [
      { name: 'namespaceAddress', type: 'address', internalType: 'address' },
      {
        name: 'id',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'exchangeToken', type: 'address', internalType: 'address' },
      {
        name: 'scalar',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'curve', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'whitelistedExchangeToken',
    type: 'function',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'whitelistedScaler',
    type: 'function',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
];
