'use strict';
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, '__esModule', { value: true });
exports.CommonApiClient = void 0;
const Client_1 = require('./api/resources/community/client/Client');
const Client_2 = require('./api/resources/comment/client/Client');
const Client_3 = require('./api/resources/thread/client/Client');
const Client_4 = require('./api/resources/reaction/client/Client');
class CommonApiClient {
  constructor(_options = {}) {
    this._options = _options;
  }
  get community() {
    var _a;
    return (_a = this._community) !== null && _a !== void 0
      ? _a
      : (this._community = new Client_1.Community(this._options));
  }
  get comment() {
    var _a;
    return (_a = this._comment) !== null && _a !== void 0
      ? _a
      : (this._comment = new Client_2.Comment(this._options));
  }
  get thread() {
    var _a;
    return (_a = this._thread) !== null && _a !== void 0
      ? _a
      : (this._thread = new Client_3.Thread(this._options));
  }
  get reaction() {
    var _a;
    return (_a = this._reaction) !== null && _a !== void 0
      ? _a
      : (this._reaction = new Client_4.Reaction(this._options));
  }
}
exports.CommonApiClient = CommonApiClient;
