/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from '../../../../core';
export const CreateGroupResponseContestManagersItemContestsItemActionsItemAction =
  core.serialization.enum_(['added', 'upvoted']);
