/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';

export declare const CreateGroupResponseSocialLinksItem: core.serialization.Schema<
  serializers.CreateGroupResponseSocialLinksItem.Raw,
  CommonApi.CreateGroupResponseSocialLinksItem
>;
export declare namespace CreateGroupResponseSocialLinksItem {
  type Raw = unknown | (string | null | undefined);
}
