/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const CreateGroupRequestRequirementsItemThresholdDataSourceThreeSourceType: core.serialization.Schema<serializers.CreateGroupRequestRequirementsItemThresholdDataSourceThreeSourceType.Raw, CommonApi.CreateGroupRequestRequirementsItemThresholdDataSourceThreeSourceType>;
export declare namespace CreateGroupRequestRequirementsItemThresholdDataSourceThreeSourceType {
    type Raw = "cw721" | "cw20";
}
