/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { CreateGroupResponseContestManagersItemContestsItemScoreItem } from "./CreateGroupResponseContestManagersItemContestsItemScoreItem";
import { CreateGroupResponseContestManagersItemContestsItemActionsItem } from "./CreateGroupResponseContestManagersItemContestsItemActionsItem";
export declare const CreateGroupResponseContestManagersItemContestsItem: core.serialization.ObjectSchema<serializers.CreateGroupResponseContestManagersItemContestsItem.Raw, CommonApi.CreateGroupResponseContestManagersItemContestsItem>;
export declare namespace CreateGroupResponseContestManagersItemContestsItem {
    interface Raw {
        contest_address: string;
        contest_id: number;
        start_time: string;
        end_time: string;
        score_updated_at?: string | null;
        score?: CreateGroupResponseContestManagersItemContestsItemScoreItem.Raw[] | null;
        actions?: CreateGroupResponseContestManagersItemContestsItemActionsItem.Raw[] | null;
    }
}
