/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';

export declare const CreateGroupResponseTermsZero: core.serialization.Schema<
  serializers.CreateGroupResponseTermsZero.Raw,
  CommonApi.CreateGroupResponseTermsZero
>;
export declare namespace CreateGroupResponseTermsZero {
  type Raw = string | '';
}
