/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';

export declare const CreateGroupResponseAddressesItemUserProfileBackgroundImage: core.serialization.ObjectSchema<
  serializers.CreateGroupResponseAddressesItemUserProfileBackgroundImage.Raw,
  CommonApi.CreateGroupResponseAddressesItemUserProfileBackgroundImage
>;
export declare namespace CreateGroupResponseAddressesItemUserProfileBackgroundImage {
  interface Raw {
    url?: string | null;
    imageBehavior?: string | null;
  }
}
