/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';
import { GetCommunitiesResponseResultsItemChainNodeBalanceType } from './GetCommunitiesResponseResultsItemChainNodeBalanceType';
import { GetCommunitiesResponseResultsItemChainNodeContractsItem } from './GetCommunitiesResponseResultsItemChainNodeContractsItem';
import { GetCommunitiesResponseResultsItemChainNodeCosmosGovVersion } from './GetCommunitiesResponseResultsItemChainNodeCosmosGovVersion';
import { GetCommunitiesResponseResultsItemChainNodeHealth } from './GetCommunitiesResponseResultsItemChainNodeHealth';

export declare const GetCommunitiesResponseResultsItemChainNode: core.serialization.ObjectSchema<
  serializers.GetCommunitiesResponseResultsItemChainNode.Raw,
  CommonApi.GetCommunitiesResponseResultsItemChainNode
>;
export declare namespace GetCommunitiesResponseResultsItemChainNode {
  interface Raw {
    id?: number | null;
    url?: string | null;
    eth_chain_id?: number | null;
    alt_wallet_url?: string | null;
    private_url?: string | null;
    balance_type?: GetCommunitiesResponseResultsItemChainNodeBalanceType.Raw | null;
    name?: string | null;
    description?: string | null;
    ss58?: number | null;
    bech32?: string | null;
    slip44?: number | null;
    cosmos_chain_id?: string | null;
    cosmos_gov_version?: GetCommunitiesResponseResultsItemChainNodeCosmosGovVersion.Raw | null;
    health?: GetCommunitiesResponseResultsItemChainNodeHealth.Raw | null;
    contracts?:
      | GetCommunitiesResponseResultsItemChainNodeContractsItem.Raw[]
      | null;
    block_explorer?: string | null;
    max_ce_block_range?: number | null;
    created_at?: string | null;
    updated_at?: string | null;
  }
}
