/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';
import { GetCommunityResponseAddressesCommunityStakesItemStakeTransactionsItemStakeDirection } from './GetCommunityResponseAddressesCommunityStakesItemStakeTransactionsItemStakeDirection';

export declare const GetCommunityResponseAddressesCommunityStakesItemStakeTransactionsItem: core.serialization.ObjectSchema<
  serializers.GetCommunityResponseAddressesCommunityStakesItemStakeTransactionsItem.Raw,
  CommonApi.GetCommunityResponseAddressesCommunityStakesItemStakeTransactionsItem
>;
export declare namespace GetCommunityResponseAddressesCommunityStakesItemStakeTransactionsItem {
  interface Raw {
    transaction_hash: string;
    community_id: string;
    stake_id?: number | null;
    address: string;
    stake_amount: number;
    stake_price?: string | null;
    stake_direction: GetCommunityResponseAddressesCommunityStakesItemStakeTransactionsItemStakeDirection.Raw;
    timestamp: number;
  }
}
