/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const GetCommunitiesResponseResultsItemAddressesItemUserProfileBackgroundImage: core.serialization.ObjectSchema<serializers.GetCommunitiesResponseResultsItemAddressesItemUserProfileBackgroundImage.Raw, CommonApi.GetCommunitiesResponseResultsItemAddressesItemUserProfileBackgroundImage>;
export declare namespace GetCommunitiesResponseResultsItemAddressesItemUserProfileBackgroundImage {
    interface Raw {
        url?: string | null;
        imageBehavior?: string | null;
    }
}
