/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
export declare const GetCommunitiesRequestBase: core.serialization.Schema<serializers.GetCommunitiesRequestBase.Raw, CommonApi.GetCommunitiesRequestBase>;
export declare namespace GetCommunitiesRequestBase {
    type Raw = "cosmos" | "substrate" | "ethereum" | "near" | "solana";
}
