/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from '../../../../core';
import { GetMembersResponseResultsItemAddressesItem } from './GetMembersResponseResultsItemAddressesItem';
export const GetMembersResponseResultsItem = core.serialization.object({
  userId: core.serialization.property('user_id', core.serialization.number()),
  profileName: core.serialization.property(
    'profile_name',
    core.serialization.string().optional(),
  ),
  avatarUrl: core.serialization.property(
    'avatar_url',
    core.serialization.string().optional(),
  ),
  addresses: core.serialization.list(
    GetMembersResponseResultsItemAddressesItem,
  ),
  groupIds: core.serialization.property(
    'group_ids',
    core.serialization.list(core.serialization.number()),
  ),
  lastActive: core.serialization.property(
    'last_active',
    core.serialization.unknown().optional(),
  ),
});
