/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateGroupResponseMetadata } from "./UpdateGroupResponseMetadata";
import { UpdateGroupResponseRequirementsItem } from "./UpdateGroupResponseRequirementsItem";
export declare const UpdateGroupResponse: core.serialization.ObjectSchema<serializers.UpdateGroupResponse.Raw, CommonApi.UpdateGroupResponse>;
export declare namespace UpdateGroupResponse {
    interface Raw {
        id?: number | null;
        community_id?: string | null;
        metadata?: UpdateGroupResponseMetadata.Raw | null;
        requirements?: UpdateGroupResponseRequirementsItem.Raw[] | null;
        is_system_managed?: boolean | null;
        created_at?: string | null;
        updated_at?: string | null;
    }
}
