/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from '../../../../core';
import { UpdateCommunityResponseGroupsItemRequirementsItemAllowData } from './UpdateCommunityResponseGroupsItemRequirementsItemAllowData';
export const UpdateCommunityResponseGroupsItemRequirementsItemAllow =
  core.serialization.object({
    data: UpdateCommunityResponseGroupsItemRequirementsItemAllowData,
  });
