/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSource } from "./UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSource";
export declare const UpdateCommunityRequestGroupsItemRequirementsItemThresholdData: core.serialization.ObjectSchema<serializers.UpdateCommunityRequestGroupsItemRequirementsItemThresholdData.Raw, CommonApi.UpdateCommunityRequestGroupsItemRequirementsItemThresholdData>;
export declare namespace UpdateCommunityRequestGroupsItemRequirementsItemThresholdData {
    interface Raw {
        threshold: string;
        source: UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSource.Raw;
    }
}
