/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from '../../../../core';
import { UpdateGroupRequestRequirementsItemThresholdData } from './UpdateGroupRequestRequirementsItemThresholdData';

export const UpdateGroupRequestRequirementsItemThreshold =
  core.serialization.object({
    data: UpdateGroupRequestRequirementsItemThresholdData,
  });
