/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from '../../../../core';

export const UpdateCommunityResponseGroupsItemRequirementsItemThresholdDataSourceTokenIdSourceType =
  core.serialization.enum_(['erc20', 'erc721', 'erc1155', 'spl']);
