/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';
import { UpdateCommunityResponseGroupsItemRequirementsItemAllow } from './UpdateCommunityResponseGroupsItemRequirementsItemAllow';
import { UpdateCommunityResponseGroupsItemRequirementsItemThreshold } from './UpdateCommunityResponseGroupsItemRequirementsItemThreshold';
export declare const UpdateCommunityResponseGroupsItemRequirementsItem: core.serialization.Schema<
  serializers.UpdateCommunityResponseGroupsItemRequirementsItem.Raw,
  CommonApi.UpdateCommunityResponseGroupsItemRequirementsItem
>;
export declare namespace UpdateCommunityResponseGroupsItemRequirementsItem {
  type Raw =
    | UpdateCommunityResponseGroupsItemRequirementsItem.Threshold
    | UpdateCommunityResponseGroupsItemRequirementsItem.Allow;
  interface Threshold
    extends UpdateCommunityResponseGroupsItemRequirementsItemThreshold.Raw {
    rule: 'threshold';
  }
  interface Allow
    extends UpdateCommunityResponseGroupsItemRequirementsItemAllow.Raw {
    rule: 'allow';
  }
}
