/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';
import { UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceOne } from './UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceOne';
import { UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThree } from './UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThree';
import { UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceTokenId } from './UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceTokenId';
import { UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceTokenSymbol } from './UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceTokenSymbol';

export declare const UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSource: core.serialization.Schema<
  serializers.UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSource.Raw,
  CommonApi.UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSource
>;
export declare namespace UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSource {
  type Raw =
    | UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceTokenId.Raw
    | UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceOne.Raw
    | UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceTokenSymbol.Raw
    | UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThree.Raw;
}
