/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from '../../../../core';
import { UpdateGroupResponseRequirementsItemThresholdDataSource } from './UpdateGroupResponseRequirementsItemThresholdDataSource';

export const UpdateGroupResponseRequirementsItemThresholdData =
  core.serialization.object({
    threshold: core.serialization.string(),
    source: UpdateGroupResponseRequirementsItemThresholdDataSource,
  });
