export const ICONS = {
  DAO: '🏛️',
  NFTs: '🖼️',
  Gaming: '👾',
  Social: '💬',
  Memes: '😹',
  AI: '🤖',
  DeFi: '💰',
  ReFi: '♻️',
  'Lending/Borrowing': '🏦',
  Staking: '📈',
  dApp: '📱',
  Technology: '🛠️',
  'Security/Auditing': '🔒',
  Governance: '⚖️',
  Marketplace: '🛍️',
  DeSci: '🔬',
  '🔛  Swaps': '🔛',
};
