/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type CreateCommunityResponseCommunityTopicsItemWeightedVoting = "stake" | "erc20";
export declare const CreateCommunityResponseCommunityTopicsItemWeightedVoting: {
    readonly Stake: "stake";
    readonly Erc20: "erc20";
};
