/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type CreateCommunityResponseCommunityContestManagersItemTopicsItemWeightedVoting =
  'stake' | 'erc20';
export declare const CreateCommunityResponseCommunityContestManagersItemTopicsItemWeightedVoting: {
  readonly Stake: 'stake';
  readonly Erc20: 'erc20';
};
