/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type CreateGroupResponseCommunityStakesItemStakeTransactionsItemStakeDirection =
  'buy' | 'sell';
export declare const CreateGroupResponseCommunityStakesItemStakeTransactionsItemStakeDirection: {
  readonly Buy: 'buy';
  readonly Sell: 'sell';
};
