/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../index';

export interface CreateCommunityResponseCommunityCommunityTagsItem {
  communityId: string;
  tagId: number;
  tag?: CommonApi.CreateCommunityResponseCommunityCommunityTagsItemTag;
}
