/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type CreateGroupRequestRequirementsItemThresholdDataSourceTokenIdSourceType =
  'erc20' | 'erc721' | 'erc1155' | 'spl';
export declare const CreateGroupRequestRequirementsItemThresholdDataSourceTokenIdSourceType: {
  readonly Erc20: 'erc20';
  readonly Erc721: 'erc721';
  readonly Erc1155: 'erc1155';
  readonly Spl: 'spl';
};
