/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from "../../../index";
export declare type GetCommunityResponseAddressesGroupsItemRequirementsItemThresholdDataSource = CommonApi.GetCommunityResponseAddressesGroupsItemRequirementsItemThresholdDataSourceTokenId | CommonApi.GetCommunityResponseAddressesGroupsItemRequirementsItemThresholdDataSourceOne | CommonApi.GetCommunityResponseAddressesGroupsItemRequirementsItemThresholdDataSourceTokenSymbol | CommonApi.GetCommunityResponseAddressesGroupsItemRequirementsItemThresholdDataSourceThree;
