/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const GetCommunityResponseAddressesCommunityStakesItemStakeTransactionsItemStakeDirection =
  {
    Buy: 'buy',
    Sell: 'sell',
  };
