/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type GetCommunitiesResponseResultsItemType = "chain" | "dao" | "token" | "offchain";
export declare const GetCommunitiesResponseResultsItemType: {
    readonly Chain: "chain";
    readonly Dao: "dao";
    readonly Token: "token";
    readonly Offchain: "offchain";
};
