/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from "../../../index";
export interface UpdateGroupResponseRequirementsItemAllow {
    data: CommonApi.UpdateGroupResponseRequirementsItemAllowData;
}
