/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../index';
export interface UpdateGroupResponseRequirementsItemThresholdDataSourceTokenId {
  sourceType: CommonApi.UpdateGroupResponseRequirementsItemThresholdDataSourceTokenIdSourceType;
  evmChainId: number;
  contractAddress: string;
  tokenId?: string;
}
