/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type UpdateCommunityRequestType =
  | 'chain'
  | 'dao'
  | 'token'
  | 'offchain';
export declare const UpdateCommunityRequestType: {
  readonly Chain: 'chain';
  readonly Dao: 'dao';
  readonly Token: 'token';
  readonly Offchain: 'offchain';
};
