/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface UpdateGroupRequestRequirementsItemThresholdDataSourceOne {
  sourceType: 'eth_native';
  evmChainId: number;
}
