/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type UpdateCommunityResponseGroupsItemRequirementsItemThresholdDataSourceThreeSourceType =
  'cw721' | 'cw20';
export declare const UpdateCommunityResponseGroupsItemRequirementsItemThresholdDataSourceThreeSourceType: {
  readonly Cw721: 'cw721';
  readonly Cw20: 'cw20';
};
