/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from "../../../index";
export interface UpdateCommunityRequestAddressesItemUser {
    id?: number;
    email?: string;
    isAdmin?: boolean;
    disableRichText?: boolean;
    emailVerified?: boolean;
    selectedCommunityId?: string;
    emailNotificationInterval?: CommonApi.UpdateCommunityRequestAddressesItemUserEmailNotificationInterval;
    promotionalEmailsEnabled?: boolean;
    isWelcomeOnboardFlowComplete?: boolean;
    profile: CommonApi.UpdateCommunityRequestAddressesItemUserProfile;
    profileTags?: CommonApi.UpdateCommunityRequestAddressesItemUserProfileTagsItem[];
    createdAt?: Date;
    updatedAt?: Date;
}
