/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const CreateThreadResponseReactionsItemAddressRole = {
  Admin: 'admin',
  Moderator: 'moderator',
  Member: 'member',
};
