apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: argocd-operator-group
  namespace: argocd
spec:
  targetNamespaces:
    - argocd
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator-subscription
  namespace: argocd
spec:
  channel: stable
  name: argocd-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic
