apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: vault
spec:
  size: 3

  image: hashicorp/vault:1.14.8
  bankVaultsImage: ghcr.io/bank-vaults/bank-vaults:latest
  serviceAccount: vault

  existingTlsSecretName: vault-tls

  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp2
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi

  volumeMounts:
    - name: vault-raft
      mountPath: /vault/file

  caNamespaces:
    - '*'

  unsealConfig:
    options:
      preFlightChecks: true
      storeRootToken: true
      secretShares: 5
      secretThreshold: 3
    aws:
      kmsKeyId: "2af407d3-75f9-499d-906e-a5a77748fa6c"
      s3Bucket: "bank-vaults-development"
      s3Prefix: "vault-operator/"
      kmsRegion: "us-east-1"
      kmsEncryptionContext: "Service=Vault"

  config:
    storage:
      raft:
        path: /vault/file
    listener:
      tcp:
        address: '0.0.0.0:8200'
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.vault:8200
    cluster_addr: 'https://${.Env.POD_NAME}:8201'
    ui: true

  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          # Allow every pod in the vault namespace to use the secret kv store
          - name: vault
            bound_service_account_names: ["vault", "vault-secrets-webhook"]
            bound_service_account_namespaces: ["vault", "vswh"]
            policies: allow_secrets
            ttl: 1h

    secrets:
      configuration:
        config:
          - name: urls
            issuing_certificates: https://vault.vault:8200/v1/pki/ca
            crl_distribution_points: https://vault.vault:8200/v1/pki/crl
          - name: internal
            common_name: vault.vault