/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';
export declare const DeleteThreadResponse: core.serialization.ObjectSchema<
  serializers.DeleteThreadResponse.Raw,
  CommonApi.DeleteThreadResponse
>;
export declare namespace DeleteThreadResponse {
  interface Raw {
    thread_id: number;
    canvas_signed_data?: string | null;
    canvas_msg_id?: string | null;
  }
}
