/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';
export declare const UpdateThreadResponseAddressRole: core.serialization.Schema<
  serializers.UpdateThreadResponseAddressRole.Raw,
  CommonApi.UpdateThreadResponseAddressRole
>;
export declare namespace UpdateThreadResponseAddressRole {
  type Raw = 'admin' | 'moderator' | 'member';
}
