/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from '../../../../core';
import { UpdateThreadResponseDiscordMetaUser } from './UpdateThreadResponseDiscordMetaUser';
export const UpdateThreadResponseDiscordMeta = core.serialization.object({
  user: UpdateThreadResponseDiscordMetaUser,
  channelId: core.serialization.property(
    'channel_id',
    core.serialization.string(),
  ),
  messageId: core.serialization.property(
    'message_id',
    core.serialization.string(),
  ),
});
