import { renderMultilineText } from 'helpers';
import { useCommonNavigate } from 'navigation/helpers';
/* eslint-disable max-len */
import React from 'react';
import { CWText } from '../components/component_kit/cw_text';
import './privacy_and_terms.scss';

const TOS = `Terms of Services
PLEASE READ THE BELOW GOVERNANCE PLATFORM SERVICES AGREEMENT VERY CAREFULLY. THE BELOW GOVERNANCE PLATFORM SERVICES AGREEMENT IS A LEGALLY BINDING CONTRACT BETWEEN YOU AND COW MOON WEALTH SOFTWARE INC. THAT SETS FORTH AND DETERMINES, AMONG OTHER THINGS:
THE TERMS AND CONDITIONS GOVERNING THE SERVICES THAT COW MOON WEALTH SOFTWARE INC. PROVIDES TO YOU AND/OR TOKEN HOLDERS WHO USE THE PLATFORM TO VOTE, DISCUSS, OR DELEGATE THEIR VALIDATION RIGHTS TO ENTITIES ON THE COW MOON WEALTH SOFTWARE INC PLATFORM; CERTAIN REPRESENTATIONS AND WARRANTIES THAT YOU ARE BEING ASKED TO MAKE TO COW MOON WEALTH SOFTWARE INC., WHICH COW MOON WEALTH SOFTWARE INC WILL RELY UPON IN PROVIDING YOU SERVICES; CERTAIN LIMITATIONS ON AND EXCLUSIONS ON THE LIABILITIES AND OBLIGATIONS THAT COW MOON WEALTH SOFTWARE INC OWES, OR MAY OTHERWISE HAVE OWED, TO YOU UNDER APPLICABLE LAW; CERTAIN LIMITATIONS ON, AND WAIVERS OF, LEGAL RIGHTS AND REMEDIES THAT YOU HAVE OR MAY OTHERWISE HAVE HAD UNDER APPLICABLE LAW; AND A
Terms of Services 1
PROVISION PROVIDING FOR WAIVER OF A JURY TRIAL OR CLASS ACTION TREATMENT IN RESPECT OF, AND MANDATORY ARBITRATION OF, ANY DISPUTE ARISING OUT OF OR RELATING TO THE GOVERNANCE PLATFORM SERVICES AGREEMENT.
BY DISCUSSING ISSUES, VOTING ON ISSUES, OR USING THE GOVERNANCE INTERFACE TO DELEGATE ANY VALIDATION RIGHTS TO COW MOON WEALTH SOFTWARE INC. (OR, IN OTHER WORDS, "BONDING" ANY TOKENS TO THE PUBLIC KEY ASSOCIATED WITH COW MOON WEALTH SOFTWARE INC. Common), YOU WILL BE CONSENTING TO BE BOUND BY, ASSENTING TO THE TERMS AND CONDITIONS OF, MAKING THE REPRESENTATIONS AND WARRANTIES SET FORTH IN, AND WILL BECOME A PARTY TO, THE GOVERNANCE PLATFORM SERVICES AGREEMENT.
IF YOU DO NOT AGREE TO ALL OF THE TERMS AND CONDITIONS OF THE GOVERNANCE PLATFORM SERVICES AGREEMENT, OR IF ANY OF THE REPRESENTATIONS AND WARRANTIES SET FORTH IN THE GOVERNANCE PLATFORM SERVICES AGREEMENT IS INACCURATE AS APPLIED TO YOU, YOU MUST NOT USE OR ACCESS THE COMMON GOVERNANCE AND SOCIAL PLATFORM.
Please contact us at hello@common.xyzfor any questions or issues regarding this GOVERNANCE PLATFORM SERVICES AGREEMENT.
GOVERNANCE AND SOCIAL PLATFORM SERVICES AGREEMENT
This Governance Platform Services Agreement (this "Agreement") is being entered into between you (the "User" or "you") and COW MOON WEALTH SOFTWARE INC Inc., a Delaware corporation ("Common"). This Agreement will, automatically and without further action of either of the parties, become effective upon you commenting or voting on posts on Common. The Common Privacy Policy is a part of this Agreement and incorporated herein by reference. Capitalized terms shall have the meanings set forth in Article I unless otherwise defined herein.
BACKGROUND
This "Background" section is included for convenience of reference only, as a partial summary of certain public sources of information published by third parties. Cosmos, Tezos, Polkadot, or any other third party supported network has not undertaken to and does not assume any obligation to independently investigate or verify the facts, circumstances, events, and conditions described herein or therein, or to provide updates hereto to reflect later events. The statements and information herein are not intended to be relied upon by any Person, whether as an accurate or complete statement of facts or otherwise, or to serve as representations, warranties or guarantees made by Common.

NOW, THEREFORE, in consideration of the mutual agreements contained below, Common and User hereby agree as follows:
ARTICLE I: DEFINITIONS AND RULES OF INTERPRETATION
Section 1.1 Certain Definitions and Rules of Interpretation. The terms defined in this Section 1.1, whenever used in this Agreement shall have the meanings set forth below:
"AAA" has the meaning assigned to such term in Section 6.2.
"Affiliate" means, with respect to any Person, any other Person directly or indirectly controlling, controlled by, or under common control with such Person.
"Atom" means any amount (including any fractional amount) of the digital token commonly known as "Atom" which is transacted in on the Cosmos Hub with transactions being recorded on the Cosmos Blockchain.

“Common Parties” means Common and its officers, directors, employees, shareholders, creditors, lenders, lawyers, advisors, insurers, predecessors, successors, affiliates, and assigns.

"Disputes" has the meaning assigned to such term in Section 6.1.
"Governmental Authority" collectively means any nation or government, any state or other political subdivision thereof, any entity exercising legislative, judicial or administrative functions of or pertaining to government, including, without limitation, any government authority, agency, department, board, commission, instrumentality, or officers or agents of the foregoing, and any court, tribunal or arbitrator(s) of competent jurisdiction, and any self- regulatory organization including officers or agents of the same.
"hereof," "herein," "hereunder," "hereby" and words of similar import will, unless otherwise stated, be construed to refer to this Agreement as a whole and not to any particular provision of this Agreement.
"include(s)" and "including" shall be construed to be followed by the words "without limitation" unless the context requires otherwise.
"Laws" means all laws, statutes, legal requirements, ordinances, rules, rulings, regulations, judgments, injunctions, orders and decrees enacted, promulgated or issued by any Governmental Authority at such time then in effect.
"or" shall be construed to be the "inclusive or" rather than "exclusive or" (i.e., shall be read as "and/or") unless the context requires otherwise.
"Organizational Documents" means the articles of incorporation, certificate of incorporation, charter, bylaws, articles of formation, certificate of formation, regulations, operating agreement, certificate of limited partnership, partnership agreement and all other similar documents, instruments or certificates executed, adopted or filed in connection with the creation, formation or organization of a Person, including any amendments or restatements of the same thereto.
"Person" means an individual or real person or a legal entity, including a corporation, partnership, trust, limited liability company, association, or a government or political subdivision or an agency or instrumentality thereof.
“Post” means to upload, publish, store, broadcast, mint or otherwise transmit information to the Service.

“User Content” means all the information, images, text, illustrations, formats, logos, designs, icons, photographs, programs, music clips, video clips and written and other materials a user Posts to the Service.
The parties hereto agree that any rule of construction to the effect that ambiguities are to be resolved against the drafting party shall not be applied in the construction or interpretation of this Agreement.
CommonARTICLE II: ACCESS AND USE OF THE SERVICE
Section 2.1 Description of the Service. Common offers a forum space where users can create and post written or image-based content for discussion. Features of the Services include:
Create a Community or Group: Users can create a community of their choice. There are no requirements from the user to create these bespoke communities aside from a name, a description, a founding member, and an image to associate with their community. Within these communities, users are free to create subgroups or “groups.” A user may gate content or access to specific functions within a community or group to certain users. Common takes no direct supervisory role over what kind of groups can be created or accessed or their value within a given community. Common
Forum: Common provides a forum wherein users can create profiles and engage each other with written text or images, and upvote that content. To engage with content users must be part of a community to be able to post within that community. A forum thread consists of an initial post, which links to the user that posted it. All ensuing comments are connected to the thread. Users can create a thread within a community by clicking “new thread.” Communities may post their own kind of threads, such as governance threads, protocol discussions, update threads, or random thread. There is no limit on the type of thread a community can create so long as that thread falls within the self-moderation rules of the community and these Terms. Users can upvote content within their community forum to make such content more easily discoverable to other users. Users can only upvote content within a community that they are a member of; however, upvoting content can and will affect how content is shown globally to users both within and outside of the originating community. Moderating a community on the Services is an unofficial voluntary position that is available to any Common user if they, or the communities they are members of, elect to do so. Moderators do not act on behalf of Common, nor are they able to act on behalf of Common or sign any third party agreements in the name of Common. Common is not responsible for moderating content within a community, so long as the groups do not violate these Terms.
Community Stake: Stake is an NFT asset that is created by a user when they engage with a Community Stake contract launched in a community on the Service. A user generates stake by purchasing or minting the stake from a smart contract with a designated funding token chosen by the community that has enabled stake. The visual image of the stake token is chosen at the time of stake enablement. If communities wish, they can deploy a Community Stake (henceforth, “stake”) smart contract on various Ethereum Virtual Machine (EVM) networks. This contract allows users to buy (or mint) NFT tokens specific to that community on common using a predetermined cryptocurrency. These NFTs are “soulbound” to the user’s digital wallet that buys them, meaning that they cannot be transferred outside of the minting user’s wallet. Users who own stake have increased upvote power, or “vote weight”, within any community that they own stake in. If a user wishes to reduce their inventory of stake in a particular community, they must burn their stake NFTs with the originating smart contract. The cost and value of stake at acquisition and redemption are determined by a bonding curve that increases or decreases in price as more users acquire or reduce their amount of stake. By default, fees derived from Community Stake go to a fee router contract that directs the funds on behalf of the administrator’s address.
Contests: Contests receive funds either directly from users or from fees generated by buying or selling Stake. Contests, on a user set interval, will pay out from their pool of funds some percent to the contest winners. Winners are determined by votes that are weighted by a secondary “vote weight calculation” contract that is also onchain for transparency plus trustfulness purposes. With the launch of contests, fees are directed toward the contests’ prize pools, to be distributed by the contests to contest winners. The fee manager/router contract can divert a share of the stake derived fees to any number of addresses on the blockchain the stake is deployed. Fees generated from Stake and direct deposits to the contests are used as part of a prize pool for iterative content contests within a community. The most upvoted content will receive a payout from the contest in whatever cryptocurrency the community chose to use.
Onchain Transactions: Community Stake requires blockchain network transactions, from the administrators of the communities that found it, because they execute a transaction onchain to reserve their namespace and found their communities. Any user that acquires community stake does so by buying tokens from an onchain smart contract. When users sell the community stake, they burn the assets and redeem some value back from the smart contract. Users can buy or mint stake from a community stake contract with the smart contract’s required funding token. This token will appear in the user’s wallet whether it is a third party wallet the user signed up with. Users can redeem or burn their stake by engaging with the originating smart contract. When they redeem or burn their stake tokens, they are returned some value from the smart contract.
Section 2.2 License to the Service. Common grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Services pursuant to these Terms. This limited authorization does not grant you any licenses, implied rights, or intellectual property rights. You agree that your use of the Services is at your sole risk and that you assume all responsibility for any reliance on the Service. We reserve all rights not expressly granted to you in and to the Services and the content within. We do not guarantee the availability, accuracy, or reliability of the Service. Except and solely to the extent such a restriction is impermissible under applicable law, you may not: (i) reproduce, distribute, publicly display, publicly perform, or create derivative works of the Service; (ii) make modifications to the Service; or (iii) interfere with or circumvent any feature of the Service, including any security or access control mechanism. If you are prohibited under applicable law from using the Service, then you may not use it.
Section 2.3 Wallet and Profile. To access most features of the Services, you will be required to verify your email address and either create or connect a digital cryptocurrency wallet (“Wallet”) to the Services to create an account. A user account may have multiple Wallet addresses associated with it. Once your account has been registered, you can add additional information to your profile. Your Wallet address, username and other information you voluntarily add to your profile may be publicly displayed on the Services when you connect your Wallet, and you consent to such public display. The profile will contain a record of all the content created by the user on the Service. For additional information about your account and profile data, please see our [insert link].
If you do not have a Wallet, you can create one using Common by signing up with Google, Discord, Twitter, Github or an email address. Common partners with Magic, a third party non-custodial wallet infrastructure provider, to allow users to create a Common account that includes a self-custodial Wallet that can be accessed via the Services (“Magic Wallet”). By creating or using a Magic Wallet in connection with the Services, you agree that you are using the Privy Wallet under Magic’s terms and conditions available at [Magic terms of services]. Only you can sign transactions and access and control your Wallet’s contents. Common does not have custody, possession, control, or otherwise have access to your Common Wallet or any assets that may be contained therein, and does not have access to or store any passwords, recovery phrases, private keys, passkeys, or any other credentials associated with user Wallets or your use of the Services. You are solely responsible for securing your Common account and Magic Wallet authentication credentials, passkeys, and private keys. You can find more information about how Magic Wallets work at https://magic.link/
Section 2.4 Using your Wallet. You must familiarize yourself with these Terms, and the technology and security protocols of any Wallet. We do not provide a crypto-wallet service and do not at any time have custody, possession, or control over your NFTs, crypto assets, or any other contents in your Wallet. You acknowledge and agree that we are not party to any transactions conducted while using our Services. We make no representations or warranties regarding how the Service will operate or be compatible with any specific Wallet.
The private keys necessary to access the assets held in a Wallet are not held by Common. You are solely responsible for maintaining the security of your Wallet, including your credentials, private key, and/or seed phrase. We are in no way liable for any acts or omissions by you in connection with your Wallet or as a result of your Wallet being compromised. Hackers may seek to access your Wallet through multiple means, including, but not limited to, phishing and other fraudulent communications. Common will never provide access to offers or promotions through discord messages or links, and you should never click on any link on discord to an offer or promotion claiming to be from common even if it appears to originate from common. You are solely responsible for any losses that arise from your clicking on any links from a third party, even if such third party appears to be common, and you are solely responsible for any losses arising from the theft or unauthorized use of your wallet credentials.
You should make contingency plans with respect to your Wallet in the event of your death or incapacity, otherwise you (and your executor, guardian, or heirs) may lose access to your Wallet, your account on the Service, and your NFTs and other purchases.
Section 2.5 User Content. You must not Post any User Content that violates these Terms or for which you do not have all the rights necessary to grant the licenses described herein. You represent and warrant that your User Content, the source and underlying materials used in creating the User Content, and our use of such content as permitted by these Terms, will not violate any rights of or cause injury to any person or entity. Common disclaims any and all liability in connection with User Content. You are solely responsible for your User Content and the consequences of providing User Content via the Services. By providing User Content via the Service, you affirm, represent, and warrant to us that:
You are the creator and owner of the User Content, or have the necessary licenses, rights, consents, and permissions to authorize Common and users of the Services to use and distribute your User Content in the manner contemplated by the Services and these Terms;
Your User Content, and the Posting or other use of your User Content as contemplated by these Terms, does not and will not: (i) infringe, violate, misappropriate, or otherwise breach any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property, contract, or proprietary right; (ii) slander, defame, libel, or invade the right of privacy, publicity or other property rights of any other person; or (iii) cause Common to violate any law or regulation or require us to obtain any further licenses from or pay any royalties, fees, compensation or other amounts or provide any attribution to any third parties; and
Your User Content is not in violation of applicable law and could not be deemed by a reasonable person to be harassing, threatening, or hateful.
Section 2.6 Specific Rules for Images and Sound Recordings. If you Post a photograph or image to the Services that includes one or more persons, you hereby grant such persons and their administrators, guardians, heirs, and trustees, if any, an irrevocable, perpetual, royalty free, fully paid-up, worldwide license to reproduce, distribute, and publicly display that photograph for personal use and through any online platform or service, including the Service, but not to promote any third-party product, good, or service. The license contained in this Section does not permit the subject of any photo or their administrators, guardians, heirs, or trustees to sell that image or photograph, whether on a standalone basis or as embodied in any product. Notwithstanding the foregoing, this Section only applies to the extent there is not a conflicting agreement between the photographer and the subject(s) of the photo. You and the subject of any photograph or other original work of authorship you Post to the Services are free to negotiate terms and conditions to supersede the provisions of this Section.
If you create and distribute an NFT that includes a sound recording, and the musical work embodied therein, or an audiovisual work embodying a sound recording and a musical work, then such musical works, sound recordings, and audiovisual works may be available through any platform or tools that access the applicable blockchain on which the NFT has been published.
Section 2.7 Responsibility for Your NFTs and Tokens. You are solely responsible for the NFTs you create using Community Stake, including for clearing the rights to any third-party content included in your NFTs, including the rights of privacy and publicity, and for any third-party claims of copyright, trademark, or other intellectual property infringement or violation of any rights of privacy or publicity. You agree to indemnify, defend, and hold Common Parties harmless from and against any and all damages, liabilities, costs, and expenses (including reasonable attorneys’ fees) arising from the minting, sale, reproduction, distribution, public display, public performance, communication to the public, advertising, marketing, promoting or other use or exploitation of your NFTs and tokens.
Section 2.8 User Content Disclaimer. We are under no obligation to edit or control User Content that you or other users Post and will not be in any way responsible or liable for User Content. Common may, however, at any time and without prior notice, screen, remove, edit, or block any User Content that in our sole judgment violates these Terms, is alleged to violate the rights of third parties, or is otherwise objectionable. You understand that, when using the Services, you will be exposed to User Content from a variety of sources and acknowledge that User Content may be inaccurate, offensive, indecent, or objectionable. You agree to waive, and do waive, any legal or equitable right or remedy you have or may have against Common with respect to User Content. If notified by a user or content owner that User Content allegedly does not conform to these Terms, we may investigate the allegation and determine in our sole discretion whether to remove the User Content, which we reserve the right to do at any time and without notice. For clarity, Common does not permit infringing activities on the Service.
Section 2.9 Monitoring Content. Common does not control and does not have any obligation to monitor: (i) User Content; (ii) any content made available by third parties; or (iii) the use of the Services by its users. You acknowledge and agree that Common reserves the right to, and may from time to time, monitor any and all information transmitted or received through the Services for operational and other purposes. If at any time Common chooses to monitor the content, then Common still assumes no responsibility or liability for content or any loss or damage incurred as a result of the use of content. During monitoring, information may be examined, recorded, copied, and used in accordance with our Privacy Policy. Common may block, filter, mute, remove or disable access to any User Content uploaded to or transmitted through the Services without any liability to the user who Posted such User Content to the Services or to any other users of the Service.
Section 2.10 Disputes Between Users. Common will not be a party to any disputes or dispute negotiations between users. You agree to resolve all such disputes with any other users of the Services directly and without involving Common in such dispute. Responsibility for the decisions you make regarding the Services rests solely with you. If Common is required to participate in any such dispute, then you will indemnify, defend, and hold the Common Parties harmless from and against any and all damages, liabilities, costs, and expenses (including reasonable attorneys’ fees) arising out of any such dispute.
Section 2.11 User Suspension and Termination. Common may at any time, with or without notice, in its sole and absolute discretion, suspend or terminate providing services to User. Common may, but is under no obligation, to provide User access to its User Content stored within the Common services upon suspension or termination of such Common services, and, at its sole and absolute discretion, Common may make User Content available to such User and set a reasonable fee for the provision of such User Content. Notwithstanding the foregoing, in the event Common suspends or terminates a User for a reason other than if Common determines in its sole discretion, that the User has violated, or likely will violate, this Agreement, then Common will use commercially reasonable efforts to provide advance notice to the User of such suspension or termination.
Section 2.12 Services Modification. Common reserves the right to modify, discontinue, improve, or change the services or terms of this Agreement at any time.
ARTICLE III: REPRESENTATIONS AND WARRANTIES OF USER
User hereby represents and warrants to Common, as of the date of entering into this Agreement and as of each date that User has any Validation Rights that are Delegated to Common:
Section 3.1 Status. If User is an individual, User is at least 18 years of age or older in the jurisdiction in which User resides and is of sound mind and body has capacity to enter into this Agreement. If User is a business entity, User is duly organized, validly existing and in good standing under the laws of the jurisdiction in which it is organized, and has all requisite power and authority for a business entity of its type to carry on its business as now conducted.
Section 3.2 Power and Authority. User has all requisite capacity, power and authority to accept the terms and conditions of this Agreement and to conduct and perform its obligations under this Agreement, and has taken, or will take, all actions necessary for the performance of User’s obligations under this Agreement. This Agreement constitutes a legal, valid and binding obligation of User enforceable against User in accordance with its terms.
Section 3.3 No Conflict; Compliance with Law. User entering into this Agreement and User's Delegation of its Validation Rights to Common does not constitute, and would not reasonably be expected to result in (with or without notice, lapse of time, or both) a breach, default, contravention or violation of any Law applicable to User, User’s corporate governance documents (if applicable), or contract or agreement to which User is a party or by which User is bound.
Section 3.4 Persons Subject to Sanctions. User (including if applicable its subsidiaries, respective directors, officers, employees, or to User’s knowledge its agents) is not, and is not 50% or more owned or controlled by, or acting on behalf of, any other Person (including the government of a Restricted Country, as defined below) who is, identified on any list of prohibited parties under any Law or by any Governmental Authorities, such as, for example, the lists maintained by the United Nations Security Council, the U.S. government (Including, without limitation, the U.S. Department of the Treasury’s Office of Foreign Assets Control’s Specially Designated Nationals and Blocked Persons List, Foreign Sanctions Evaders List, Sectoral Sanctions Identification List), the European Union (EU) or its member states (including the Consolidated List of Persons, Groups, and Entities Subject to EU Financial Sanctions), the UK’s Consolidated Sanctions List, and the government of User's home country. User is not, and is not owned or controlled by, organized by, established by, or acting on behalf of, any other Person who is, located, ordinarily resident, organized, established, or domiciled in Cuba, Iran, North Korea, Sudan, Syria, or the Crimea (including Sevastopol), Donetsk, and Luhansk regions of Ukraine, or any other country or jurisdiction against which the U.S. maintains economic sanctions or an arms embargo (“Restricted Countries”). User's Atoms are not derived from, and do not otherwise represent the proceeds of, any activities done in violation or contravention of any Law.
Section 3.5 No Claim, Loan, Ownership Interest or Investment Purpose. User understands and agrees that neither User's Delegation of Validation Rights and Voting Rights to Common, nor Common's provision of Services hereunder: (a) represents or constitutes a loan or a contribution of capital to, or other investment in, Common; (b) provides User with any ownership interest, equity, security, or right to, claim, or interest in the assets, rights, properties, revenues or profits of, or voting rights whatsoever in, Common; or (c) creates or implies any fiduciary or other agency relationship between Common or any of its directors, officers, employees, agents or affiliates and User or entitles User to any fiduciary duty or similar duty on the part any of the foregoing Persons. User is not entering into this Agreement or Delegating Validation Rights or Voting Rights to Common for the purpose of making an investment with respect to Common or its securities, but solely and exclusively wishes to receive the Services from Common. User understands and agrees that Common will not accept, maintain, manage, or take custody of or interest in any Block Rewards or Transaction Fees on behalf of User, and has no responsibility or control over whether the Cosmos Hub distributes Block Rewards or Transaction Fees to User. Common's sole obligation under this Agreement is to perform the Services, upon the terms and conditions set forth in this Agreement, which may, but is not guaranteed to, result in User receiving Block Rewards and Transaction Fees directly through the operations of the Cosmos Hub.
Section 3.6 Non-Reliance. User is knowledgeable, experienced, and sophisticated in using and evaluating the blockchain networks and tokens and similar technologies and services. User has conducted its own thorough independent investigation and analysis of each blockchain network and the other matters contemplated by this Agreement in determining to Delegate any Validation Rights or Voting Rights to Common and to enter into this Agreement, and has not relied upon any information, statement, omission, representation or warranty, express or implied, written or oral, made by or on behalf of Common in connection therewith, or by any other third-party Person.
Section 3.7 Prohibited Conduct. User will at all times comply with all applicable Laws, regulations, rules, governmental orders, and industry standards including, without limitation, securities, derivatives, commodities, privacy and data security, intellectual property, and consumer protection laws and regulations. You may not access or use the Services for any purpose other than that for which we make the Services available. As a user of the Services, you agree not to:

use the Services in a manner inconsistent with any applicable laws or regulations, including using the Services to interact with the Common protocol in a manner that is illegal or otherwise prohibited by law or regulation in any jurisdiction, or that is intended to harass, abuse, intimidate or violate the legal rights or privacy of any person;
trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords;
harass, threaten, demean, embarrass, bully, or otherwise harm any other user of the Service;
violate, encourage others to violate, or provide instructions on how to violate, any right of a third party, including by infringing or misappropriating any third-party intellectual property right;
circumvent, disable, or otherwise interfere with security-related features of the Services;
use any software or networking techniques, including use of a Virtual Private Network (VPN) to modify your internet protocol address or otherwise circumvent or attempt to circumvent this prohibition;
make improper use of our support services or submit false reports of abuse or misconduct;
upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with any party’s uninterrupted use and enjoyment of the Services or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Services;
attempt to impersonate another user or person or use the username of another user;
interfere with, disrupt, or create an undue burden on the Services or the networks or services connected to the Services including denial of service attacks;
sell or otherwise transfer the access granted under these Terms or any Common content or any right or ability to view, access, or use any Materials;
attempt to bypass any measures of the Services designed to prevent or restrict access to the Services, or any portion of the Services, including by: (i) disabling or circumventing features that prevent or limit use, printing or copying of any Content; or (ii) reverse engineering or otherwise attempting to discover the source code of any portion of the Services except to the extent that the activity is expressly permitted by applicable law;
make any unauthorized use of the Services, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses; or
attempt to do or assist or permit any person to engage in any of the acts described in this Section.

Section 3.8 Identity Verification. Common may require identity verification from the User in order to obtain or continue using certain Common services, to comply with legal obligations of Common or the User, or in circumstances when Common believes a user may be engaging in conduct that is not in compliance with this Agreement. You agree to fully cooperate in and comply with the identity verification processes currently in place and as may be established by Common from time to time pursuant to this Agreement or otherwise, and promptly provide all information requested by Common in connection therewith, which may include, without limitation, [personally identifiable information such as name, email, address, telephone number, date of birth, taxpayer identification or social security number, official government-issued photo identification or bank account information deemed reasonably helpful to Common to fulfill its obligations. You hereby represent that such information you provide is or will be at the time of providing it, accurate and complete.
ARTICLE IV: INTELLECTUAL PROPERTY
Section 4.1 Common’s Ownership. The design of Common’s services and all text, graphics, information, content, processes, and other material displayed on or contained in the services (including without limitation, the look and feel, all text, photographs, images, video and audio) are owned by Common or their respective licensors and protected by copyright, trademark, and possibly patent and other laws and may not be used except as permitted in this Agreement or with prior written permission of the owner of such material. All rights are reserved. You may not modify the information or materials displayed on, or contained in, the Common services in any way, or reproduce or publicly display, perform, or distribute or otherwise use any such information or materials for any public or commercial purpose. You may not copy, reproduce, publish, transmit, distribute, perform, display, post, modify, create derivative works from, sell, license, or otherwise exploit the Common services. Any unauthorized use of any such information or materials may violate copyright laws, trademark laws, laws of privacy and publicity, and other Laws and regulations and is prohibited. In the event of a violation of these Laws and regulations, Common reserves the right to seek all remedies available by law and in equity. For so long as you are in compliance with this Agreement, Common grants you a limited, non-exclusive, non-transferable, non-sublicensable, non-assignable, revocable license to access and use the Common services. This license is automatically revoked for your noncompliance with this Agreement, or Common’s suspension or termination of services to you.
Section 4.2 Feedback. If you submit comments, ideas, insights, bug reports, or other feedback to Common related to its services (collectively, “Feedback”), you assign ownership in such Feedback to Common and agree that Common may use, disclose, and otherwise exploit such Feedback for any purpose at its own discretion without any additional compensation or notice to you.
Section 4.3 Digital Millennium Copyright Act. Common will process and investigate notices of alleged copyright infringement and will take appropriate action under the Digital Millennium Copyright Act (“DMCA”). If you are an intellectual property rights holder and believe your rights have been infringed, please send your claim of copyright infringement to our designated agent by mail to [DMCA agent address], email to [DMCA agent email], or by phone to [DMCA agent phone]. You must provide the following when making your claim under the DMCA: (1) a physical or electronic signature of a person authorized to act on behalf of the copyright owner; (2) identification of the copyrighted work claimed to have been infringed; (3) identification of the material that is claimed to be infringing or to be the subject of the infringing activity, and that is to be removed or access to which is to be disabled; (4) information reasonably sufficient to permit Common to contact the copyright owner, such as an address, telephone number, and, if available, an email address; (5) a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or law to locate the material; and (6) a statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the copyright owner. Please note that Common does not determine copyright ownership or resolve infringement disputes.
Section 4.4 User Content. Subject to Section 4.2, Common does not assert ownership in information, art, media, files, NFTs, or other content that you create, mint, post, transmit, and/or display via the Common services (“User Content”). You grant Common a worldwide, non-exclusive, sublicensable, assignable, irrevocable, royalty-free license to use, copy, modify, and display User Content for Common’s business purposes including, without limitation, to provide, support, enhance, and promote the Common services, to comply with legal obligations, and for any other purpose contemplated by Common’s Privacy Policy and this Agreement. You represent and warrant that you have all necessary rights and permissions, or are otherwise legally entitled, to generate, use, and/or disclose the User Content and to grant the foregoing license, and that the User Content and Common’s license to such User Content does not violate any laws or infringe the privacy, publicity, or intellectual property rights of any Person.
ARTICLE V: DISCLAIMER, LIMITATIONS, AND INDEMNIFICATION
Section 5.1 Liability Disclaimers. You agree that Common will have no responsibility or liability for the actions of other users of its services, actions of third parties (including third parties providing platforms or services integrated with or available via the Common services), authorized or unauthorized use of the services, performance of cryptographic or blockchain-based systems, or your use or reliance upon any third-party scripts, code, content, or other information. Any advice or recommendations made by Common are for your convenience only, and you agree that Common is not liable for any damages you incur from your reliance upon them. Common does not endorse, adopt, or guarantee any third-party goods, services, products, offers, or information made available via its services. You must keep confidential all User’s credentials associated with the services, and Common is not responsible for the security, transfer, or maintenance of your virtual currency assets or private keys, and you agree Common is not responsible or liable for any claimed or actual loss thereof.
Section 5.2 Disclaimer of Warranties. The Common services are provided on an “as is” and “as available” basis. The Common services are based on novel and developing technologies that may be more likely than others to contain bugs, errors, vulnerabilities, and systematic and other risks. You hereby acknowledge and agree that you use the Common services at your own risk. Common does not represent, warrant, or guarantee that you will see any economic benefit or avoid any economic loss from your use of its services. Common does not represent or warrant that its services will be uninterrupted, secure, or error free. Common expressly disclaims, to the fullest extent allowable by law any and all, promises, representations and warranties, express or implied or statutory, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose, data accuracy, system integration, title, quiet enjoyment, and noninfringement.
Section 5.3 No Consequential, Incidental or Punitive Damages. Notwithstanding anything to the contrary contained herein, Common shall not be liable to any Person, whether in contract, tort (including pursuant to any cause of action alleging negligence), warranty or otherwise, for special, incidental, consequential,
indirect, punitive or exemplary damages (including but not limited to lost data, lost profits or savings, loss of business or other economic loss) arising out of or related to this Agreement, whether or not Common has been advised or knew of the possibility of such damages, and regardless of the nature or origin of the cause of action or theory asserted.
Section 5.4 Limitation of Liability. Common's liability for damages under this Agreement shall in all cases be limited to, and under no circumstances shall exceed, the greater of (i) the portion of fees actually received by Common that demonstrably arose by virtue of the User's particular Delegation of its particular Validation Rights to Common or (ii) fifty dollars ($50) (USD).
Section 5.5 Indemnification. To the extent permitted by Law, you agree, severally and not jointly with other Users, to indemnify, defend, and hold harmless Common and its affiliates, subsidiaries, owners, officers, directors, service providers, agents, and employees from any and all liabilities, damages, claims, losses, costs, and expenses (including reasonable attorneys’ fees and costs or other expenses reasonably incurred thereby in connection with investigating or defending any claim or proceeding from which damages may result as such expenses are incurred) arising out of related to your (i) use of the Common services, (ii) actual or alleged violation of this Agreement, (iii) User Content, or (iv) negligence or willful misconduct. You acknowledge and agree that Common may control the defense or settlement of any indemnified claims at your cost. You hereby agree to fully cooperate with Common in the defense and settlement of any indemnified claims. If Common elects to permit you to control the defense and settlement of the indemnified claims, Common may participate in the defense using counsel of its choosing and at its own cost and you may not agree to any settlement that places obligations upon Common without Common’s prior written consent.

ARTICLE VI: DISPUTE RESOLUTION
Section 6.1 Agreement to Binding, Exclusive Arbitration. Except as set forth in Section 6.5, all unresolved claims, disputes and controversies directly or indirectly arising out of or in connection with or directly or indirectly relating to this Agreement, any of the matters or transactions contemplated by this Agreement (for the avoidance of doubt, including any claim seeking to invalidate, or alleging that, all or any part of this Agreement is unenforceable, void or voidable), or your relationship with Common (such claims, disputes and controversies, collectively, "Disputes") shall be finally settled by binding arbitration, rather than in court. The arbitrator, and not any federal, state or local court, agency or other Governmental Authority, shall have exclusive authority to resolve all Disputes. The parties hereby acknowledge, represent and warrant that they understand that: (a) there is no judge or jury in arbitration, and, absent this mandatory provision, the parties would have the right to sue in court and have a jury trial concerning Disputes; (b) in some instances, the costs of arbitration could exceed the costs of litigation; (c) the right to discovery may be more limited in arbitration than in court; and (d) court review of an arbitration award is limited. The Federal Arbitration Act and federal arbitration law apply to this Agreement. Notwithstanding anything to the contrary set forth in this Section 6.1, either party may seek relief in a small claims court for Disputes within the scope of that court's jurisdiction. Prior to initiating a Dispute against Common, you agree to contact Common at [email] and provide a detailed statement of your proposed Dispute and resolution so that Common may attempt to resolve your Dispute prior to arbitration. If the parties have been unable to reach a resolution of your Dispute within sixty days after the date of Common’s receipt of your email, and you have acted in good faith to negotiate a settlement, you may submit your Dispute for arbitration in accordance with this Section 6. Any statute of limitations will be tolled during this sixty-day pre-Dispute negotiation period.
Section 6.2 Arbitration Procedures. Either party may initiate an arbitration proceeding by delivering written notice to the other party, whereupon the parties shall reasonably cooperate to select an arbitrator mutually agreed upon by the parties, and submit the relevant Dispute to such arbitrator. In the event the parties are unable to agree on the selection of an arbitrator within 30 days from the filing of a demand for arbitration, the American Arbitration Association (“AAA”) shall appoint the arbitrator, provided such arbitrator has reasonable experience in transactions provided for in this Agreement and the Dispute. Any such arbitration shall be administered by the American Arbitration Association in accordance with the provisions of its Commercial Arbitration Rules then in effect and the supplementary procedures for consumer related disputes of the AAA, excluding any rules or procedures governing or permitting class actions. Arbitrations with an amount in controversy of less than one million dollars ($1,000,000) (USD) will be conducted before a single arbitrator without an opportunity for appeal. Arbitrations with an amount in controversy equal to or greater than one million dollars ($1,000,000) (USD) will be conducted before a panel of three arbitrators with an opportunity for appeal. There shall be limited discovery prior to the arbitration hearing as follows: (a) exchange of witness lists and copies of documentary evidence and documents relating to the issues to be arbitrated, (b) depositions of all party witnesses, and (c) such other depositions as may be allowed by the arbitrators upon a showing of good cause. The arbitrator(s) will issue a reasoned opinion accompanying their judgment. Each party will bear its own attorneys’ fees and other costs associated with the arbitration. Notwithstanding the foregoing, Common may seek its attorneys' fees, costs and necessary disbursements in addition to any other relief to which such party may be entitled if the arbitrator determines your Dispute is frivolous. The arbitrator shall be empowered to grant whatever relief would be available in a court under law or in equity. The arbitrator's award shall be written and reasoned, and binding on the parties, and may be entered into by any party as a judgment in any court of competent jurisdiction.

Section 6.3 Seat of Arbitration. The seat of arbitration shall be New York County, New York. The parties may mutually choose to have the arbitration of any Dispute conducted by telephone, based on written submissions, or at a mutually agreed location other than New York County, New York. User hereby agrees to submit to the personal jurisdiction for any equitable action sought in any federal or state court in New York County, New York, including in order to compel arbitration, to stay proceedings pending arbitration, or to confirm, modify, vacate or enter judgment on the award entered by the arbitrator.
Section 6.4 Confidentiality of Arbitration. Except to the extent necessary to enforce their respective rights under this Agreement or as otherwise required by applicable Law, the parties undertake to maintain confidentiality as to the existence, outcome, and events of the arbitration proceedings and as to all records, materials, submissions, correspondence and evidence relating to the arbitration proceedings. This provision shall survive the termination of the arbitral proceedings.
Section 6.5 Class Action Waiver. The parties agree that any arbitration or other permitted action with respect to any Dispute shall be conducted in their individual capacities only and not as a class action or other representative action, and the parties expressly waive their right to file a class action or seek relief on a class basis. EACH PARTY AGREES THAT SUCH PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN SUCH PARTY'S INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.
If any court or arbitrator(s) makes a final, binding and non-appealable determination that the class action waiver set forth in this paragraph is void or unenforceable for any reason or that an arbitration can proceed on a class basis, then the arbitration provision set forth above shall be deemed null and void with respect to any Dispute that would thus be required to be resolved by arbitration on a class basis, and the parties shall be deemed to have not agreed to arbitrate such Dispute. In the event that, as a result of the application of the immediately preceding sentence or otherwise, any Dispute is not subject to arbitration, the parties hereby agree to submit to the personal and exclusive jurisdiction of and venue in the federal and state courts located in New York County, New York and to accept service of process by certified or registered mail with respect to such Dispute, and hereby waive any and all jurisdictional and venue defenses otherwise available with respect to such Dispute. Each party will provide necessary then current contact information to facilitate service of process.
ARTICLE VII: MISCELLANEOUS
Section 7.1 Governing Law. This Agreement shall be governed in all respects, including as to validity, interpretation and effect, by the internal laws of the State of New York, without giving effect to its principles or rules of conflict of laws, to the extent such principles or rules are not mandatorily applicable by statute and would permit or require the application of the laws of another jurisdiction.
Section 7.2 Successors and Assigns. This Agreement shall inure to the benefit of the parties, and their respective permitted successors, permitted assigns, permitted transferees and permitted delegates and shall be binding upon all of the foregoing persons and any Person who may otherwise succeed to any right, obligation or liability under this Agreement by operation of law or otherwise. Nothing in this Agreement, express or implied, is intended to confer upon any party other than the parties hereto or their respective successors and permitted assignees any rights, remedies, obligations or liabilities under or by reason of this Agreement, except as expressly provided herein. User shall not share or provide a copy of, or transfer to, any Person the private key associated with any Atoms with respect to which Validation Rights are Delegated to Common without notifying such Person that such Person shall be bound by and become a party to this Agreement by virtue of making any use of such private keys while such Delegation remains in effect. Except as set forth above, no rights, obligations or liabilities of User may be assigned, transferred or delegated to any Person without the prior written consent of Common. Common may freely assign, transfer or delegate its rights, obligations and liabilities under this Agreement to the maximum extent permitted by applicable Law.
Section 7.3 Entire Agreement. This Agreement constitutes the full and entire understanding and agreement between the parties relating to the subject matter hereof and supersedes and expressly cancels all prior or contemporaneous agreements and understandings, both written and oral, between the parties with respect to the subject matter hereof.
Section 7.4 Severability and Survivability. If any provision of this Agreement is determined by a court of competent jurisdiction to be invalid, illegal, inoperative or unenforceable for any reason, such invalidity, illegality, inoperability or unenforceability shall not affect any other provision of this Agreement, and Common shall have the right to modify this Agreement to effect the original intent of the parties as closely as possible in an acceptable manner in order that the transactions contemplated hereby be consumed as originally contemplated to the fullest extent possible. Provisions of this Agreement which by their nature would survive termination hereof, including, without limitation, indemnification, confidentiality, limitation of liability, disclaimers of warranties, irrevocable intellectual property licenses, and dispute resolution provisions will be deemed to survive.
Section 7.5 No Partnership and No Agency or Implied Duties. Nothing in this Agreement and no action taken by the parties pursuant to this Agreement shall constitute, or be deemed to constitute, a partnership, association, joint venture or other co-operative entity between any of the parties. Nothing in this Agreement and no action taken by the parties pursuant to this Agreement shall constitute, or be deemed to constitute or appoint, either party the agent of the other party for any purpose or to owe the other party any agency, bailment, trust or other implied duties, including any fiduciary duty. No party has, pursuant to this Agreement, any authority or power to bind or to contract in the name of the other party, except as set forth herein including Section 5.5.
Section 7.6 Publications and Notifications. The parties shall reasonably and mutually agree to any press release or publication that jointly involves the names, brands or officers of both parties. For clarity, you may not issue any press release or publication involving the name, brand, identity, or officers, directors, or other service providers of Common without Common’s prior approval. Correspondence and notifications from Common to you, whether as a result of a dispute or otherwise intended to be official correspondence, may be sent by electronic mail (including pdf or any electronic signature complying with the U.S. federal ESIGN Act of 2000, e.g., www.docusign.com) or common forms of social media (Skype, Slack, WhatsApp) at any applicable address or username provided by you through Common's website. Any correspondence or notification from Common to you so delivered shall be deemed to have been duly and validly delivered and be valid and effective for all purposes. Correspondence and notifications to Common must be by electronic mail to [email] or by overnight courier or certified/registered mail to [address].
Section 7.7 Force Majeure. Common shall not incur any liability or penalty for not performing any act or fulfilling any obligation hereunder by reason of any occurrence that is not within its control (including any provision of any present or future law or regulation or any act of any Governmental Authority, any act of God or war or terrorism, or the unavailability, disruption or malfunction of the Internet, the World Wide Web or any other electronic network the Cosmos Network or any aspect thereof, any event or act outside the control of Common affecting as a whole the industries in which Common operates that precludes Common from performing acts or fulfilling obligations in this Agreement, or any consensus attack, or hack, or denial-of-service or other attack, on the Cosmos Network or any aspect thereof, or on the software and infrastructure that enables Common to operate the Validating NodeInfo), it being understood that Common shall use commercially reasonable efforts, consistent with accepted practices in the industries in which Common operates, as applicable, to resume performance and comply with this Agreement as soon as reasonably practicable under the circumstances.
Section 7.8 Taxes. User is responsible to determine any and all applicable taxes, if any, which apply to your use of the Common services and report and remit such applicable taxes to the appropriate tax authority or Governmental Authority.
Section 7.9 Amendments. This Agreement may only be amended, modified, altered or supplemented by Common. The most current version of this Agreement will be posted on the Common website which you agree constitutes notice of an update, regardless of the provisions of Section 7.6. Such revised versions of this Agreement are effective and binding upon you immediately upon posting. User’s use of Common’s services after Common posts an updated version of this Agreement constitutes the User’s acceptance of the updated version. Common may, but is not obligated, to provide additional notice of an update in a manner of its choosing such as by posting a notice on its website for a period of time or sending an email to users, or as otherwise permitted by Section 7.6.
Section 7.10 No Waiver. No failure on the part of any Person to exercise any power, right, privilege or remedy under this Agreement, and no delay on the part of any Person in exercising any power, right, privilege or remedy under this Agreement, shall operate as a waiver of such power, right, privilege or remedy; and no single or partial exercise of any such power, right, privilege or remedy shall preclude any other or further exercise thereof or of any other power, right, privilege or remedy. No Person shall be deemed to have waived on such party’s own behalf any claim arising out of this Agreement, or any power, right, privilege or remedy under this Agreement, unless the waiver of such claim, power, right, privilege or remedy is expressly set forth in a written instrument duly executed and delivered on behalf of such Person; and any such waiver shall not be applicable or have any effect except in the specific instance in which it is given.
Section 7.11 No Investment Advice. The Services is not intended to provide legal, tax, investment or insurance advice. Nothing on the Services should be construed as an offer to sell, a solicitation of an offer to buy, or a recommendation for any financial instrument by us or any third party. You are solely responsible for determining whether any transaction is appropriate for you based on your personal objectives, financial circumstances, and risk tolerance. You are solely responsible for determining what, if any, taxes apply to your transactions using the Service. You should consult your legal, investment or tax professional regarding your specific situation. We do not make any representations regarding the benefits or results that you or any third party shall receive from the Services.
Section 7.12 Valuation of Stake, or any other NFTs, and Assumption of Risk. Common does not endorse, approve of, or take any responsibility in determining any particular NFT’s value, or make any warranty about the suitability of any NFT for ownership or trading. The prices and value of any NFTs are volatile and subjective and have no guaranteed value. Common does not and cannot guarantee that any NFT purchased through the Services will retain any particular value. You acknowledge that to the extent any NFT has value, any NFT may drop in value for many reasons, and Common will have no responsibility for determining value or making up any losses in value to you. You agree to assume all risk associated with the use and value of NFTs, including the risk that an NFT may have no value in the future. You also agree not to create or use NFTs in any way that would violate applicable laws, including US securities laws.
Section 7.13 Novel and Experimental Technology. The Service, Common, and Common Network rely on novel and experimental technology that may contain bugs, viruses, Trojan horses, or other vulnerabilities, and may be subject to hacks, phishing attempts or other malicious activity, that could result in a complete loss of the crypto assets that you use in connection with the Services, Common, or any protocol based on Common.xyz. By using Common, you acknowledge and agree to use such a novel and experimental technology at your own risk. You further acknowledge and agree that there are certain risks native to cryptographic or blockchain-based systems, which include but are not limited to, private key security, high price volatility, technological vulnerabilities, cybersecurity attacks, and other forms of malicious activity present in the crypto asset ecosystem (e.g., scams, rug pulls). Please do your own due diligence before engaging with the Service, or Common, whether directly or via any third-party products.
Section 7.14 Modification of Terms. Common reserves the right to change or modify these Terms at any time and in our sole discretion. If we make material changes to these Terms, we will use reasonable efforts to provide notice of such changes, such as by providing notice through the Services or updating the “Last Updated” date at the beginning of these Terms. By continuing to access or use the Service, you confirm your acceptance of the revised Terms and all of the terms incorporated therein by reference effective as of the date these Terms are updated. It is your sole responsibility to review the Terms from time to time to view such changes and to ensure that you understand the terms and conditions that apply when you access or use the Service.`;

const TermsPage = () => {
  const navigate = useCommonNavigate();

  return (
    <div className="TermsPage">
      <div className="forum-container">
        <CWText type="h3">Terms of Service</CWText>
        <CWText>Posted on 7/10/2024</CWText>
        {renderMultilineText(TOS)}
        <CWText
          onClick={() => {
            window.open(
              'https://drive.google.com/file/d/1Sd9dnyOKONc8880QwDiVSB3mrq1Pzb86/view?usp=sharing',
              '_blank',
            );
          }}
          className="link"
        >
          See Full Policy
        </CWText>
        <CWText
          onClick={() => {
            navigate('/tos-1-26-2023');
          }}
          className="link"
        >
          Previous Privacy Policy
        </CWText>
      </div>
    </div>
  );
};

export default TermsPage;
