export const EdgewareChainNotificationTypes = {
  Council: [
    'edgeware-collective-approved',
    'edgeware-collective-disapproved',
    'edgeware-collective-executed',
    'edgeware-collective-member-executed',
    'edgeware-collective-proposed',
    'edgeware-collective-voted',
    'edgeware-election-candidacy-submitted',
    'edgeware-election-empty-term',
    'edgeware-election-member-kicked',
    'edgeware-election-member-renounced',
    'edgeware-election-new-term',
  ],
  Democracy: [
    'edgeware-democracy-cancelled',
    'edgeware-democracy-executed',
    'edgeware-democracy-not-passed',
    'edgeware-democracy-passed',
    'edgeware-democracy-proposed',
    'edgeware-democracy-started',
    'edgeware-democracy-tabled',
  ],
  Preimage: [
    'edgeware-preimage-invalid',
    'edgeware-preimage-missing',
    'edgeware-preimage-noted',
    'edgeware-preimage-reaped',
    'edgeware-preimage-used',
  ],
  Signaling: [
    'edgeware-signaling-commit-started',
    'edgeware-signaling-new-proposal',
    'edgeware-signaling-voting-completed',
    'edgeware-signaling-voting-started',
  ],
  Treasury: [
    'edgeware-treasury-awarded',
    'edgeware-treasury-proposed',
    'edgeware-treasury-rejected',
    'edgeware-treasury-reward-minting',
    'edgeware-treasury-reward-minting-v2'
  ],
  Validator: [
    'edgeware-bonded',
    'edgeware-reward',
    'edgeware-slash',
    'edgeware-unbonded',
  ],
  VotingDelegation: [
    'edgeware-vote-delegated',
  ],
};

export const PolkadotChainNotificationTypes = {
  Council: [
    'polkadot-collective-approved',
    'polkadot-collective-disapproved',
    'polkadot-collective-executed',
    'polkadot-collective-member-executed',
    'polkadot-collective-proposed',
    'polkadot-collective-voted',
    'polkadot-election-candidacy-submitted',
    'polkadot-election-empty-term',
    'polkadot-election-member-kicked',
    'polkadot-election-member-renounced',
    'polkadot-election-new-term',
  ],
  Democracy: [
    'polkadot-democracy-cancelled',
    'polkadot-democracy-executed',
    'polkadot-democracy-not-passed',
    'polkadot-democracy-passed',
    'polkadot-democracy-proposed',
    'polkadot-democracy-started',
    'polkadot-democracy-tabled',
  ],
  Preimage: [
    'polkadot-preimage-invalid',
    'polkadot-preimage-missing',
    'polkadot-preimage-noted',
    'polkadot-preimage-reaped',
    'polkadot-preimage-used',
  ],
  Treasury: [
    'polkadot-treasury-awarded',
    'polkadot-treasury-proposed',
    'polkadot-treasury-rejected',
  ],
  Validator: [
    'polkadot-bonded',
    'polkadot-reward',
    'polkadot-slash',
    'polkadot-unbonded',
  ],
  VotingDelegation: [
    'polkadot-vote-delegated',
  ],
};

export const KusamaChainNotificationTypes = {
  Council: [
    'kusama-collective-approved',
    'kusama-collective-disapproved',
    'kusama-collective-executed',
    'kusama-collective-member-executed',
    'kusama-collective-proposed',
    'kusama-collective-voted',
    'kusama-election-candidacy-submitted',
    'kusama-election-empty-term',
    'kusama-election-member-kicked',
    'kusama-election-member-renounced',
    'kusama-election-new-term',
  ],
  Democracy: [
    'kusama-democracy-cancelled',
    'kusama-democracy-executed',
    'kusama-democracy-not-passed',
    'kusama-democracy-passed',
    'kusama-democracy-proposed',
    'kusama-democracy-started',
    'kusama-democracy-tabled',
  ],
  Preimage: [
    'kusama-preimage-invalid',
    'kusama-preimage-missing',
    'kusama-preimage-noted',
    'kusama-preimage-reaped',
    'kusama-preimage-used',
  ],
  Treasury: [
    'kusama-treasury-awarded',
    'kusama-treasury-proposed',
    'kusama-treasury-rejected',
  ],
  Validator: [
    'kusama-bonded',
    'kusama-reward',
    'kusama-slash',
    'kusama-unbonded',
  ],
  VotingDelegation: [
    'kusama-vote-delegated',
  ],
};

export const KulupuChainNotificationTypes = {
  Council: [
    'kulupu-collective-approved',
    'kulupu-collective-disapproved',
    'kulupu-collective-executed',
    'kulupu-collective-member-executed',
    'kulupu-collective-proposed',
    'kulupu-collective-voted',
    'kulupu-election-candidacy-submitted',
    'kulupu-election-empty-term',
    'kulupu-election-member-kicked',
    'kulupu-election-member-renounced',
    'kulupu-election-new-term',
  ],
  Democracy: [
    'kulupu-democracy-cancelled',
    'kulupu-democracy-executed',
    'kulupu-democracy-not-passed',
    'kulupu-democracy-passed',
    'kulupu-democracy-proposed',
    'kulupu-democracy-started',
    'kulupu-democracy-tabled',
  ],
  Preimage: [
    'kulupu-preimage-invalid',
    'kulupu-preimage-missing',
    'kulupu-preimage-noted',
    'kulupu-preimage-reaped',
    'kulupu-preimage-used',
  ],
  Treasury: [
    'kulupu-treasury-awarded',
    'kulupu-treasury-proposed',
    'kulupu-treasury-rejected',
  ],
  Validator: [
    'kulupu-bonded',
    'kulupu-reward',
    'kulupu-slash',
    'kulupu-unbonded',
  ],
  VotingDelegation: [
    'kulupu-vote-delegated',
  ],
};
