'use strict';
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, '__esModule', { value: true });
exports.CreateCommunityRequestType = void 0;
exports.CreateCommunityRequestType = {
  Chain: 'chain',
  Dao: 'dao',
  Token: 'token',
  Offchain: 'offchain',
};
