'use strict';
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, '__esModule', { value: true });
exports.CreateCommunityResponseCommunityDefaultPage = void 0;
exports.CreateCommunityResponseCommunityDefaultPage = {
  DefaultAllDiscussionsView: 'default_all_discussions_view',
  DefaultSummaryView: 'default_summary_view',
  Homepage: 'homepage',
};
