'use strict';
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, '__esModule', { value: true });
exports.CreateGroupResponseContestManagersItemContestsItemActionsItemAction =
  void 0;
exports.CreateGroupResponseContestManagersItemContestsItemActionsItemAction = {
  Added: 'added',
  Upvoted: 'upvoted',
};
