'use strict';
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, '__esModule', { value: true });
exports.CreateCommunityResponseCommunityHasHomepage = void 0;
exports.CreateCommunityResponseCommunityHasHomepage = {
  True: 'true',
  False: 'false',
};
