'use strict';
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, '__esModule', { value: true });
exports.GetCommunitiesRequestOrderBy = void 0;
exports.GetCommunitiesRequestOrderBy = {
  ProfileCount: 'profile_count',
  LifetimeThreadCount: 'lifetime_thread_count',
  Last30DayThreadCount: 'last_30_day_thread_count',
};
