'use strict';
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, '__esModule', { value: true });
exports.UpdateTopicResponseTopicWeightedVoting = void 0;
exports.UpdateTopicResponseTopicWeightedVoting = {
  Stake: 'stake',
  Erc20: 'erc20',
};
