'use strict';
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, '__esModule', { value: true });
exports.UpdateCommunityResponseGroupsItemRequirementsItemThresholdDataSourceThreeSourceType =
  void 0;
exports.UpdateCommunityResponseGroupsItemRequirementsItemThresholdDataSourceThreeSourceType =
  {
    Cw721: 'cw721',
    Cw20: 'cw20',
  };
