/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Signer } from "ethers";
import { Contract } from "ethers";
import type { Provider } from "@ethersproject/providers";

import type { ITransferHook } from "../ITransferHook";

export class ITransferHook__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITransferHook {
    return new Contract(address, _abi, signerOrProvider) as ITransferHook;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "onTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
