export const codeBlockLanguages: { [key: string]: string } = {
  clojure: 'Clojure',
  cobol: 'Cobol',
  dart: 'Dart',
  diff: 'Diff',
  dockerfile: 'Dockerfile',
  erlang: 'Erlang',
  go: 'Go',
  groovy: 'Groovy',
  haskell: 'Haskell',
  htmlmixed: 'HTML',
  idl: 'IDL',
  js: 'JavaScript',
  jinja2: 'Jinja2',
  kotlin: 'Kotlin',
  lua: 'Lua',
  markdown: 'Markdown',
  pascal: 'Pascal',
  perl: 'Perl',
  php: 'PHP',
  properties: 'Properties (INI)',
  protobuf: 'Protobuf',
  python: 'Python',
  ruby: 'Ruby',
  rust: 'Rust',
  sass: 'Sass',
  scheme: 'Scheme',
  scss: 'SCSS',
  shell: 'Shell',
  sql: 'SQL',
  xml: 'XML',
  yaml: 'YAML',
};
