/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         communityId: "community_id",
 *         groupId: 1
 *     }
 */
export interface DeleteGroupRequest {
  communityId: string;
  groupId: number;
}
