apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-dns
  namespace: ingress-nginx
spec:
  secretName: wildcard-cert-dns-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: '*.unique.rocks'
  dnsNames:
    - '*.unique.rocks'
