/* eslint-disable max-len */

import m from 'mithril';
import mixpanel from 'mixpanel-browser';
import { renderMultilineText } from 'helpers';

const TermsOfService = `
PLEASE READ THE BELOW GOVERNANCE PLATFORM SERVICES AGREEMENT VERY CAREFULLY. THE BELOW GOVERNANCE PLATFORM SERVICES AGREEMENT IS A LEGALLY BINDING CONTRACT BETWEEN YOU AND COMMONWEALTH LABS THAT SETS FORTH AND DETERMINES, AMONG OTHER THINGS:


THE TERMS AND CONDITIONS GOVERNING THE SERVICES THAT COMMONWEALTH LABS PROVIDES TO TOKEN HOLDERS WHO USE THE PLATFORM TO VOTE, DISCUSS, OR DELEGATE THEIR VALIDATION RIGHTS TO ENTITIES ON THE COMMONWEALTH PLATFORM; CERTAIN REPRESENTATIONS AND WARRANTIES THAT YOU ARE BEING ASKED TO MAKE TO COMMONWEALTH LABS, WHICH COMMONWEALTH LABS WILL RELY UPON IN PROVIDING YOU SERVICES; CERTAIN LIMITATIONS ON AND EXCLUSIONS OF THE LIABILITIES AND OBLIGATIONS THAT COMMONWEALTH LABS OWES OR MAY OTHERWISE HAVE OWED TO YOU UNDER APPLICABLE LAW; CERTAIN LIMITATIONS ON AND WAIVERS OF LEGAL RIGHTS AND REMEDIES THAT YOU HAVE OR MAY OTHERWISE HAVE HAD UNDER APPLICABLE LAW; AND A PROVISION PROVIDING FOR WAIVER OF A JURY TRIAL OR CLASS ACTION TREATMENT IN RESPECT OF, AND MANDATORY ARBITRATION OF, ANY DISPUTE ARISING OUT OF OR RELATING TO THE GOVERNANCE PLATFORM SERVICES AGREEMENT.


BY DISCUSSING ISSUES, VOTING ON ISSUES, OR USING THE GOVERNANCE INTERFACE TO DELEGATE ANY VALIDATION RIGHTS TO COMMONWEALTH LABS (OR, IN OTHER WORDS, "BONDING" ANY TOKENS TO THE PUBLIC KEY ASSOCIATED WITH COMMONWEALTH LABS), YOU WILL BE CONSENTING TO BE BOUND BY, ASSENTING TO THE TERMS AND CONDITIONS OF, MAKING THE REPRESENTATIONS AND WARRANTIES SET FORTH IN, AND WILL BECOME A PARTY TO, THE BELOW GOVERNANCE PLATFORM SERVICES AGREEMENT.


IF YOU DO NOT AGREE TO ALL OF THE TERMS AND CONDITIONS OF THE GOVERNANCE PLATFORM SERVICES AGREEMENT, OR IF ANY OF THE REPRESENTATIONS AND WARRANTIES SET FORTH THE GOVERNANCE PLATFORM SERVICES AGREEMENT IS INACCURATE AS APPLIED TO YOU, YOU MUST NOT USE THE COMMONWEALTH GOVERNANCE PLATFORM.


Please contact us at hello@commonwealth.im for any questions or issues.


GOVERNANCE PLATFORM SERVICES AGREEMENT

This Governance Platform Services Agreement (this "Agreement") is being entered into between you (the "User" or "you") and Commonwealth Labs., a Delaware corporation ("Commonwealth"). This Agreement will, automatically and without further action of either of the parties, become effective upon you commenting or voting on posts on Commonwealth.


BACKGROUND

This "Background" section is included for convenience of reference only, as a partial summary of certain public sources of information published by third parties, and Cosmos, Tezos, Polkadot, or any other supported network has not undertaken to and does not assume any obligation to independently investigate or verify the facts, circumstances, events, and conditions described herein or therein or to provide updates hereto to reflect later events. The statements and information herein are not intended to be relied upon by any Person, whether as an accurate or complete statement of facts or otherwise, or to serve as representations, warranties or guarantees made by Commonwealth.



A. The "Cosmos Blockchain" is a digital blockchain ledger whereon transactions in digital tokens are recorded and stored as a result of the coordinated activities of a distributed, peer-to-peer network (the "Cosmos Hub") of software clients ("Nodes") running the Tendermint Core consensus protocol ("Tendermint Core"). Nodes on other blockchain networks running Tendermint Core (such networks, "Hubs") or running other consensus protocols (such networks, "Zones") may communicate with Nodes on the Cosmos Hub and write transactions to the Cosmos Blockchain through the Tendermint Application BlockChain Interface ("ABCI"). Collectively, the Cosmos Hub, the Hubs, the Zones and their respective nodes and blockchains form a set of interoperable blockchain networks that are referred to as the "Cosmos Network," which has been described as an "internet of blockchains."
B. Atoms are the native Governance Platform/governance token on the Cosmos Hub. Each Atom represents a limited license on the Cosmos Hub for the owner to validate and propose the addition of blocks to the Cosmos Blockchain ("Validation Rights") and to vote upon proposals regarding the governance of the Cosmos Hub, including proposals for assigning particular values to parameters that determine how Tendermint Core is implemented on the Cosmos Hub, the spending of a reserve fund (the "Reserve Fund") and other related matters ("Voting Rights").
C. Atoms existing at the time of the launch of the Cosmos Hub were minted by the Interchain Foundation, a Swiss foundation (the "ICF") and have been allocated among certain of the ICF's donors and service providers, including All in Bits Inc., a Delaware corporation ("AIB"), which develops Tendermint Core and the ABCI for profit pursuant to a commercial relationship with the ICF. Additional Atoms will be automatically created by operation of the Cosmos Hub and distributed over time as rewards to Persons who exercise their Validation Rights. Because third parties such as ICF and AIB are responsible for researching, developing, marketing, selling, licensing and distributing the software and tokens relevant to the Cosmos Network, the use of such software and tokens by Commonwealth and the User may be subject to obligations imposed by, or rights belonging to ICF, AIB or such other third parties. Additionally, because Voting Rights may be exercised by Atom holders to establish contractual restrictions on the use of the Cosmos Network, including by voting to approve a natural-language "Cosmos Constitution," the use of the Cosmos Network may be subject to obligations imposed by, or rights belonging to, such Atom holders or other third parties as the result of such future activity. Collectively, the current and future rights of and obligations of the User and Commonwealth to third parties involved with the Cosmos Network are referred to in this Agreement as the "Cosmos Terms and Conditions".
D. For purposes of network efficiency, only a limited number of Nodes (the "Maximum Validator Number") are permitted to exercise Validation Rights on the Cosmos Hub at any given time (the "Validator Nodes"). Holders of Atoms that do not run Validator Nodes can nevertheless exercise their Validation Rights through a process known as "delegation." The Validation Rights associated with any particular Atoms are "Delegated" to a Validator NodeInfo when the owner of such Atoms (the "Delegator") transmits a "delegate" transaction to the Cosmos Hub that publicly associates (or "bonds") those Atoms with the known public key address belonging to such Validator NodeInfo. In effect, Delegation allows an Atom holder to exercise its Validation Rights by means of a Validator NodeInfo that is owned, operated and maintained by a third party. Delegation does not entitle or enable a Validator NodeInfo to obtain custody, possession or control of the relevant Atoms.
E. The Delegation of Validation Rights to a Validating NodeInfo also entails a contingent delegation of Voting Rights to the Validation NodeInfo. In the event that the Delegator fails to affirmatively vote the Delegator's Atoms otherwise on the Cosmos Hub with respect to a given Proposal, the Delegator will be automatically deemed to have voted in the same manner as the Validating NodeInfo.
F. Upon the addition of a new block to the Cosmos Blockchain, the Cosmos Hub automatically issues to each Delegator who then had Validation Rights Delegated to an eligible Validator NodeInfo: (1) additional Atoms that are newly minted as an increase to the total supply of Atoms (such Atoms, the "Block Rewards") and (2) additional Atoms, Photons or other tokens, as applicable, that were transferred by the senders of the transactions included in that block as transaction fees (the "Transaction Fees").
G. To compensate the owner of the Validator NodeInfo for its service, the Cosmos Hub automatically deducts a percentage (the "Service Percentage") of the Block Rewards and Transaction Fees that would otherwise be payable to the Delegators and issues the deducted tokens to the Validator NodeInfo owner as a service fee for running the Validator NodeInfo (the "Service Fee"). The owner of each Validator NodeInfo sets its own Service Percentage and may increase or decrease its Service Percentage from time to time by setting the relevant parameters on the Cosmos Hub. Block Rewards and Transaction Fees may also be subject to other deductions imposed by the Cosmos Hub from time to time, including a "tax" that contributes a portion of such Block Rewards or Transaction Fees to the Reserve Pool. Other than with respect to the Service Fees, Delegation does not entitle or enable a Validator NodeInfo to obtain custody, possession or control of any Block Rewards or Transaction Fees generated by exercising the Validation Rights of a Delegator. The amount of tokens included in the Block Rewards and Transaction Fees at any particular time is variable and depends on a number of factors, including the then-current parameters of Tendermint Core as implemented on the Cosmos Hub, network demand and the preferences and choices of users sending transactions to for inclusion in the Cosmos Blockchain.
H. The security model of the Cosmos Network relies upon the assumption that Validator Nodes representing a supermajority of Validation Rights are online/available and operating honestly for the benefit of the Cosmos Network at all times (the "Honest Supermajority Assumption"). In order to incentivize Atom holders to Delegate their Validation Rights to Validator Nodes that will be operated in accordance with the Honest Supermajority Assumption, the Cosmos Hub automatically imposes penalties ("Penalties") on an Atom holder if its chosen Validator NodeInfo operates in a manner that may undermine the Honest Supermajority Assumption or otherwise might impair the functioning of the Cosmos Network. Depending on the circumstances and the present and future values assigned to relevant parameters on the Cosmos Hub, Penalties of various severities may be imposed on a Delegator due to a variety of behaviors by its chosen Validating NodeInfo, not all of which are in the control of the Persons (such as Commonwealth) operating the Validating NodeInfo, including: (1) "double-signing" (signing two blocks at the same block height on two forks of one chain; (2) excessive unavailability/downtime (measured as absence of the Validating NodeInfo's signature a certain number of times in a certain number of blocks); (3) a cybersecurity failure resulting in actual or potential "hacks" or cyber-attacks against the Validating NodeInfo that qualify for a bounty to be paid by the Delegators; and (4) a failure to vote on Governance Proposals. The Penalties imposed on the Delegators of a Validating NodeInfo as a result of such behaviors may include: (x) temporary loss of eligibility of the Validator NodeInfo and its Delegators to receive Block Rewards and Transaction Fees for a certain number of blocks, which would represent an irreversible opportunity cost to the Validator NodeInfo and its Delegators; (y) the Persons operating the Validator NodeInfo temporarily or permanently losing eligibility to operate a Validator NodeInfo, which would require the Delegators to Delegate their Validation Rights to a different Validator NodeInfo in order to exercise their Validation Rights and remain eligible to receive Block Rewards and Transaction Fees; and (z) the "slashing" of all or a portion of the Delegators' Atoms that are bonded to the Validator NodeInfo, meaning that the Delegators would forfeit and permanently lose all right and title to and interest in all or a portion of such Atoms, the Validation Rights and Voting Rights associated with such Atoms and all future Block Rewards and Transaction Fees that the Delegator could otherwise have earned by exercising Validation Rights with respect to those Atoms.
I. Commonwealth operates the software and infrastructure necessary to run a Validator NodeInfo on the Cosmos Hub. During the times that Commonwealth is selected on the Cosmos Hub to run a Validator NodeInfo, Commonwealth wishes to provide services to the User by enabling the User to exercise its Validation Rights on the Cosmos Hub through Commonwealth's Validator NodeInfo in exchange for Service Fees. The User is a holder of Atoms who wishes to Delegate Atoms to Commonwealth in order to be eligible to receive Block Rewards and Transaction Fees by exercising its Validation Rights on the Cosmos Hub.
NOW, THEREFORE, in consideration of the mutual agreements contained below, Commonwealth and User hereby agree as follows:
ARTICLE I: DEFINITIONS AND RULES OF INTERPRETATION

Section 1.1 Certain Definitions and Rules of Interpretation. The terms defined in this Section 1.1, whenever used in this Agreement shall have the meanings set forth below:
"AAA" has the meaning assigned to such term in Section 5.2.
"Affiliate" means, with respect to any Person, any other Person directly or indirectly controlling, controlled by or under common control with such Person.
"Atom" means any amount (including any fractional amount) of the digital token commonly known as "Atom" which is transacted in on the Cosmos Hub with transactions being recorded on the Cosmos Blockchain.
"Disputes" has the meaning assigned to such term in Section 5.1.
"Governmental Authority" means any nation or government, any state or other political subdivision thereof, any entity exercising legislative, judicial or administrative functions of or pertaining to government, including, without limitation, any government authority, agency, department, board, commission or instrumentality, and any court, tribunal or arbitrator(s) of competent jurisdiction, and any self- regulatory organization.
"hereof," "herein," "hereunder," "hereby" and words of similar import will, unless otherwise stated, be construed to refer to this Agreement as a whole and not to any particular provision of this Agreement.
"include(s)" and "including" shall be construed to be followed by the words "without limitation" unless the context requires otherwise.
"Laws" means all laws, statutes, legal requirements, ordinances, rules, rulings, regulations, judgments, injunctions, orders and decrees enacted, promulgated or issued by any Governmental Authority.
"or" shall be construed to be the "inclusive or" rather than "exclusive or" (i.e., shall be read as "and/or") unless the context requires otherwise.
"Organizational Documents" means the articles of incorporation, certificate of incorporation, charter, bylaws, articles of formation, certificate of formation, regulations, operating agreement, certificate of limited partnership, partnership agreement and all other similar documents, instruments or certificates executed, adopted or filed in connection with the creation, formation or organization of a Person, including any amendments thereto.
"Person" means an individual or legal entity or person, including a government or political subdivision or an agency or instrumentality thereof.
The parties hereto agree that any rule of construction to the effect that ambiguities are to be resolved against the drafting party shall not be applied in the construction or interpretation of this Agreement.


ARTICLE II. COMMONWEALTH SERVICES

Section 2.1 Services. Subject to the terms and conditions of this Agreement, including the User Eligibility Conditions, during the times, if any, that Commonwealth is among the Persons selected on the Cosmos Hub to operate a Validating NodeInfo, Commonwealth will use commercially reasonable efforts to operate the Validating NodeInfo in a manner intended to facilitate the exercise, through the Validating NodeInfo, of User's Validation Rights with respect to the Atoms of User, if any, that are Delegated to Commonwealth as of such times (such operation of the Validating NodeInfo, the "Services").
Section 2.2 Conditions Precedent to Commonwealth's Obligations to Perform Services.
(a) Commonwealth shall not have any obligation to perform the Services at any time if any one or more of the following conditions precedent is not satisfied as of such time: the representations and warranties of User set forth in Article III are accurate and complete as of all times on and after the date of this Agreement while User has Validation Rights that are Delegated to Commonwealth; Commonwealth is included in the Maximum Validator Number of Persons selected to operate a Validator NodeInfo on the Cosmos Hub; and neither User's Delegation of its Validation Rights to Commonwealth, nor Commonwealth's performance of Services for User, constitute, or would be reasonably expected to result in (with or without notice, lapse of time, or both) a breach, default, contravention or violation of any Law applicable to User or Commonwealth, or contract or agreement to which User or Commonwealth is a party or by which User or Commonwealth is bound, including this Agreement and the Cosmos Agreements.


User acknowledges and agrees that the technologies and activities involved in the Cosmos Network are novel, experimental, and speculative, and that therefore there is significant uncertainty regarding the application of existing Law thereto. Accordingly, without limiting the generality of the foregoing or any other provision of this Agreement, circumstances under which one or more of the aforementioned conditions precedents may fail to be satisfied or Commonwealth have a claim against User for an improper Delegation include: (x) that Atoms, Photons or one or more tokens involved in the Cosmos Network are determined under any potentially applicable Law to constitute securities and the activity of serving as a Validating NodeInfo therefore may require certain registrations, licenses, or permits not possessed by Commonwealth; (y) that User is or becomes subject to sanctions (such as by having been added to the "OFAC list") imposed by any relevant Governmental Authority; and (z) that under relevant anti-money laundering, know-your-customer or similar rules or regulations, Commonwealth is deemed to have a "money transmitter" or similar status, but cannot reasonably comply with the associated obligations due to the decentralized, open-source, permissionless design of the Cosmos Network.
(b) User acknowledges and understands that, due to the permissionless, decentralized design of the Cosmos Network: (a) any Person holding Atoms can anonymously Delegate their Validation Rights to Commonwealth on the Cosmos Hub, and accordingly Commonwealth does not under ordinary circumstances have an ability to prevent any such Person from receiving the Services; and (b) Commonwealth may be unable to ascertain important information regarding User, including User's name, country of origin, country of residence, age, good standing, legal status, affiliations, entity type and criminal history. Accordingly, there may be periods of time during which one or more of the conditions described in clause "(a)" above is not satisfied, but Commonwealth is unaware of such fact and continues rendering Services to User.
(c) In the event that User could reasonably expect that any of the conditions described in clause "(a)" above is not satisfied prior to Delegating Validation Rights to Commonwealth, User shall not Delegate any Validation Rights to Commonwealth and, in the event that, after Delegating any Validation Rights to Commonwealth, User could reasonably expect that any of such conditions has ceased to be satisfied, User shall immediately revoke such Delegation.
(d) Without limiting the generality of Section 6.10, User acknowledges and agrees that Cosmos shall not be deemed to have waived any of the conditions described in clause "(a)" above, or waived or released any claim, right, power, privilege or remedy related thereto, by virtue of providing Services to User while having no specific knowledge that such condition is not satisfied with respect to User, and may terminate its Services to User after learning of such non-satisfaction regardless of how long such condition has not been satisfied. User may be liable to Commonwealth to monetary or other damages in the event that User Delegates its Validation Rights to Commonwealth, or fails to revoke such a Delegation that was previously made, when any of the conditions described in clause "(a)" above is not satisfied.
Section 2.3 No Guarantee of Validator NodeInfo Status. There can be no guarantee or assurance that, and Commonwealth is not making any representation, warranty or promise to the effect that, Commonwealth will serve as a Validator NodeInfo at all or for any particular period of time. Commonwealth's failure to become or remain a Validator NodeInfo shall not constitute a breach of any provision of this Agreement or otherwise give rise to any liability or obligation of Commonwealth to User.
Section 2.4 Fork Handling. The Hubs and Zones of the Cosmos Network, and Tendermint Core, like other decentralized, open-source blockchains and blockchain protocols, may be subject to "forks." Forks occur when some or all Persons running the software clients for a particular blockchain adopt a new client or a new version of an existing client that: (a) changes the protocol rules in backwards-compatible or backwards-incompatible manner that affects which transactions can be added into later blocks, how later blocks are added to the blockchain, or other matters relating to the future operation of the protocol; or (b) reorganizes or changes past blocks to alter the history of the blockchain. Some forks are "contentious" and thus may result in two or more persistent alternative versions of the protocol or blockchain, either of which may be viewed as or claimed to be the legitimate or genuine continuation of the original. Commonwealth may not be able to anticipate, control or influence the occurrence or outcome of forks of the Cosmos Hub or other Hubs or Zones on the Cosmos Network, and does not assume any risk, liability or obligation in connection therewith. Without limiting the generality of the foregoing, Commonwealth does not assume any responsibility notify User of pending, threatened or actual forks. Commonwealth will respond to any forks as Commonwealth determines in its sole and absolute discretion, and Commonwealth shall not have any obligation or liability to User if such response benefits Commonwealth to the detriment of User. Without limiting the generality of the foregoing, Commonwealth's possible and permissible responses to a fork include, among others: (i) continuing to serve as a Validating NodeInfo on both chains; (ii) serving as a Validating NodeInfo only on one chain; (iii) ceasing to be a Validating NodeInfo on both chains; or (iv) switching from serving as Validating NodeInfo on one such chain to serving as a Validating NodeInfo on the other, or vice versa, based on various factors. In the event of a fork of the Cosmos Hub, it is possible (but not guaranteed) that the same number of Atoms/Validation Rights that were bonded/Delegated to Commonwealth on the original chain will by default be bonded/Delegated to Commonwealth on the forked chain. In the event that Commonwealth does not choose to support both chains, User's Validation Rights and Voting Rights may go unexercised on the chain Commonwealth does not support, and User may temporarily or permanently lose Atoms, Block Rewards or Transaction Fees on the unsupported chain. User assumes full responsibility to independently remain apprised of and informed about possible forks, and to manage User's own interests in connection therewith, including by potentially retracting a Delegation to the public key of Commonwealth's Validator NodeInfo on a fork that Commonwealth does not support.
Section 2.5 Selective Code Deference. Except as otherwise set forth in this Agreement, as between Commonwealth and User, the results of operation of the Cosmos Network shall be determinative of the rights and obligations of, and shall be final, binding upon and non-appealable by, each of the parties to this Agreement. Without limiting the generality of the foregoing, User acknowledges and agrees that the taking of any action or the exercise by Commonwealth of any right, power or privilege that is possible to be taken or exercised by a Validating NodeInfo on the Cosmos Network shall not constitute a breach, violation or contravention of this Agreement or any duty or obligation owed by Commonwealth to User, and that any portion of Block Rewards, Transaction Fees or other awards distributed to Commonwealth by operation of the Cosmos Network constitute Service Fees and shall be the sole and exclusive property of Commonwealth, and User shall have no claim on, rights to or interests therein. Conversely, if there would otherwise be any legally binding contract or agreement between or involving User and Commonwealth that is implied by, or embodied in, the machine, assembly or other code involved in, or the results of operation of, the Cosmos Network or any Hub or Zone thereof that conflicts or is inconsistent in any respect with this Agreement, this Agreement shall prevail over such other contract or agreement.


ARTICLE III: REPRESENTATIONS AND WARRANTIES OF USER

User hereby represents and warrants to Commonwealth, as of the date of entering into this Agreement and as of each date that User has any Validation Rights that are Delegated to Commonwealth:
Section 3.1 Status. If User is an individual, User is of legal age in the jurisdiction in which User resides and is of sound mind and body. If User is a business entity, User is duly organized, validly existing and in good standing under the laws of the jurisdiction in which it is organized, and has all requisite power and authority for a business entity of its type to carry on its business as now conducted.
Section 3.2 Power and Authority. User has all requisite capacity, power and authority to accept the terms and conditions of this Agreement and to carry out and perform its obligations under this Agreement. This Agreement constitutes a legal, valid and binding obligation of User enforceable against User in accordance with its terms.
Section 3.3 No Conflict; Compliance with Law. User entering into this Agreement and User's Delegation of its Validation Rights to Commonwealth does not constitute, and would not reasonably be expected to result in (with or without notice, lapse of time, or both) a breach, default, contravention or violation of any Law applicable to User, or contract or agreement to which User is a party or by which User is bound.
Section 3.4 Persons Subject to Sanctions. User is not, and is not owned or controlled by, or acting on behalf of, any other Person who is, identified on any list of prohibited parties under any Law or by any Governmental Authorities, such as, for example, the lists maintained by the United Nations Security Council, the U.S. government (including the U.S. Treasury Department's Specially Designated Nationals list and Foreign Sanctions Evaders list), the European Union (EU) or its member states, and the government of User's home country. User is not, and is not owned or controlled by, or acting on behalf of, any other Person who is, located, ordinarily resident, organized, established, or domiciled in Cuba, Iran, North Korea, Sudan, Syria, the Crimea region (including Sevastopol) or any other country or jurisdiction against which the U.S. maintains economic sanctions or an arms embargo. User's Atoms are not derived from, and do not otherwise represent the proceeds of, any activities done in violation or contravention of any Law.
Section 3.5 No Claim, Loan, Ownership Interest or Investment Purpose. User understands and agrees that neither User's Delegation of Validation Rights and Voting Rights to Commonwealth, nor Commonwealth's provision of Services hereunder: (a) represents or constitutes a loan or a contribution of capital to, or other investment in, Commonwealth; (b) provides User with any ownership interest, equity, security, or right to or interest in the assets, rights, properties, revenues or profits of, or voting rights whatsoever in, Commonwealth; or (c) creates or implies any fiduciary or other agency relationship between Commonwealth or any of its directors, officers, employees, agents or Affiliates and User or entitles User to any fiduciary duty or similar duty on the part any of the foregoing Persons. User is not entering into this Agreement or Delegating Validation Rights or Voting Rights to Commonwealth for the purpose of making an investment with respect to Commonwealth or its securities, but solely wishes to receive the Services from Commonwealth. User understands and agrees that Commonwealth will not accept or take custody over any Block Rewards or Transaction Fees on behalf of User, and has no responsibility or control over whether the Cosmos Hub distributes Block Rewards or Transaction Fees to User. Commonwealth's sole obligation under this Agreement is to perform the Services, upon the terms and conditions set forth in this Agreement, which may, but is not guaranteed to, result in User receiving Block Rewards and Transaction Fees directly through the operations of the Cosmos Hub.
Section 3.6 Non-Reliance. User is knowledgeable, experienced and sophisticated in using and evaluating the Cosmos Network and similar technologies. User has conducted its own thorough independent investigation and analysis of the Cosmos Network and the other matters contemplated by this Agreement in determining to Delegate any Validation Rights or Voting Rights to Commonwealth and enter into this Agreement, and has not relied upon any information, statement, omission, representation or warranty, express or implied, written or oral, made by or on behalf of Commonwealth in connection therewith.


ARTICLE IV: DISCLAIMER AND LIMITATIONS

Section 4.1 No Consequential, Incidental or Punitive Damages. Notwithstanding anything to the contrary contained herein, Commonwealth shall not be liable to any Person, whether in contract, tort (including pursuant to any cause of action alleging negligence), warranty or otherwise, for special, incidental, consequential, indirect, punitive or exemplary damages (including but not limited to lost data, lost profits or savings, loss of business or other economic loss) arising out of or related to this Agreement, whether or not Commonwealth has been advised or knew of the possibility of such damages, and regardless of the nature of the cause of action or theory asserted.
Section 4.2 Limitation of Liability. Commonwealth's liability for damages under this Agreement shall in all cases be limited to, and under no circumstances shall exceed, the portion of Service Fees actually received by Commonwealth that demonstrably arose by virtue of the User's particular Delegation of its particular Validation Rights to Commonwealth.


ARTICLE V: DISPUTE RESOLUTION

Section 5.1 Agreement to Binding, Exclusive Arbitration. Except as set forth in Section 5.5(b), all claims, disputes and controversies directly or indirectly arising out of or in connection with or directly or indirectly relating to this Agreement or any of the matters or transactions contemplated by this Agreement (for the avoidance of doubt, including any claim seeking to invalidate, or alleging that, all or any part of this Agreement is unenforceable, void or voidable) (such claims, disputes and controversies, collectively, "Disputes") shall be finally settled by binding arbitration, rather than in court. The arbitrator, and not any federal, state or local court, agency or other Governmental Authority, shall have exclusive authority to resolve all Disputes. The parties hereby acknowledge, represent and warrant that they understand that: (a) there is no judge or jury in arbitration, and, absent this mandatory provision, the parties would have the right to sue in court and have a jury trial concerning Disputes; (b) in some instances, the costs of arbitration could exceed the costs of litigation; (c) the right to discovery may be more limited in arbitration than in court; and (d) court review of an arbitration award is limited. The Federal Arbitration Act and federal arbitration law apply to this Agreement. Notwithstanding anything to the contrary set forth in this Section 5.1, either party may seek relief in a small claims court for Disputes within the scope of that court's jurisdiction.
Section 5.2 Arbitration Procedures. Either party may initiate an arbitration proceeding by delivering written notice to the other party, whereupon the parties shall reasonably cooperate to select an arbitrator and submit the relevant Dispute to such arbitrator. In the event the parties are unable to agree on the selection of an arbitrator within 15 days from the filing of a demand for arbitration, the AAA shall appoint the arbitrator. Any such arbitration shall be administered by the American Arbitration Association in accordance with the provisions of its Commercial Arbitration Rules and the supplementary procedures for consumer related disputes of the American Arbitration Association (the "AAA"), excluding any rules or procedures governing or permitting class actions. Commonwealth will not seek attorneys' fees and costs in arbitration unless the arbitrator determines the claims are frivolous. The arbitrator shall be empowered to grant whatever relief would be available in a court under law or in equity. The arbitrator's award shall be written and reasoned, and binding on the parties, and may be entered by any party as a judgment in any court of competent jurisdiction.
Section 5.3 Seat of Arbitration. The seat of arbitration shall be [New York], [New York]. The Delegator may choose to have the arbitration of any Dispute conducted by telephone, based on written submissions, or at a mutually agreed location; provided, however, that Commonwealth may opt to transfer the venue of any arbitration hearing to [New York], [New York] in the event that it agrees to pay any additional fees or costs User may reasonably incur as a result of the change in venue, as determined by the arbitrator, and, subject to the foregoing, User hereby agrees to submit to the personal jurisdiction of any federal or state court in [New York] County, [New York], in order to compel arbitration, to stay proceedings pending arbitration, or to confirm, modify, vacate or enter judgment on the award entered by the arbitrator.
Section 5.4 Confidentiality of Arbitration. Except to the extent necessary to enforce their respective rights under this Agreement or as otherwise required by applicable Law, the parties undertake to maintain confidentiality as to the existence and events of the arbitration proceedings and as to all submissions, correspondence and evidence relating to the arbitration proceedings. This provision shall survive the termination of the arbitral proceedings.
Section 5.5 Class Action Waiver.
The parties agree that any arbitration or other permitted action with respect to any Dispute shall be conducted in their individual capacities only and not as a class action or other representative action, and the parties expressly waive their right to file a class action or seek relief on a class basis. EACH PARTY AGREES THAT SUCH PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN SUCH PARTY'S INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.
If any court or arbitrator makes a final, binding and non-appealable determination that the class action waiver set forth in this paragraph is void or unenforceable for any reason or that an arbitration can proceed on a class basis, then the arbitration provision set forth above shall be deemed null and void with respect to any Dispute that would thus be required to be resolved by arbitration on a class basis, and the parties shall be deemed to have not agreed to arbitrate such Dispute. In the event that, as a result of the application of the immediately preceding sentence or otherwise, any Dispute is not subject to arbitration, the parties hereby agree to submit to the personal and exclusive jurisdiction of and venue in the federal and state courts located in [New York], [New York] and to accept service of process by mail with respect to such Dispute, and hereby waive any and all jurisdictional and venue defenses otherwise available with respect to such Dispute.


ARTICLE VI: MISCELLANEOUS

Section 6.1 Governing Law. This Agreement shall be governed in all respects, including as to validity, interpretation and effect, by the laws of the State of [New York], without giving effect to its principles or rules of conflict of laws, to the extent such principles or rules are not mandatorily applicable by statute and would permit or require the application of the laws of another jurisdiction.
Section 6.2 Successors and Assigns.
This Agreement shall inure to the benefit of the parties, and their respective permitted successors, permitted assigns, permitted transferees and permitted delegates and shall be binding upon all of the foregoing persons and any Person who may otherwise succeed to any right, obligation or liability under this Agreement by operation of law or otherwise. User shall not share or provide a copy of, or transfer to, any Person the private key associated with any Atoms with respect to which Validation Rights are Delegated to Commonwealth without notifying such Person that such Person shall be bound by and become a party to this Agreement by virtue of making any use of such private keys while such Delegation remains in effect.
Except as set forth in Section 6.2(a), no rights, obligations or liabilities of User may be assigned, transferred or delegated to any Person without the prior written consent of Commonwealth. Commonwealth may freely assign, transfer or delegate its rights, obligations and liabilities under this Agreement to the maximum extent permitted by applicable Law.
Section 6.3 Entire Agreement. This Agreement constitutes the entire agreement between the parties relating to the subject matter hereof and supersedes all prior or contemporaneous agreements and understandings, both written and oral, between the parties with respect to the subject matter hereof.
Section 6.4 Severability. If any provision of this Agreement is determined by a court of competent jurisdiction to be invalid, inoperative or unenforceable for any reason, Commonwealth shall have the right to modify this Agreement so as to effect the original intent of the parties as closely as possible in an acceptable manner in order that the transactions contemplated hereby be consumed as originally contemplated to the fullest extent possible.
Section 6.6 No Partnership and No Agency or Implied Duties. Nothing in this Agreement and no action taken by the parties pursuant to this Agreement shall constitute, or be deemed to constitute, a partnership, association, joint venture or other co-operative entity between any of the parties. Nothing in this Agreement and no action taken by the parties pursuant to this Agreement shall constitute, or be deemed to constitute, either party the agent of the other party for any purpose or to owe the other party any agency, bailment, trust or other implied duties, including any fiduciary duty. No party has, pursuant to this Agreement, any authority or power to bind or to contract in the name of the other party.
Section 6.7 Publications and Notifications, Fees and Expenses. The parties shall agree to any press release or publication that jointly involves the names, brands or officers of both parties. Written correspondence and notifications between the parties, whether as a result of a dispute or otherwise intended to be official correspondence, may be email or common forms of social media (Skype, Slack, WhatsApp) at any applicable address or username provided by such party through Commonwealth's website. Each party shall be solely liable for all of its own fees, costs and otherwise in connection with this Agreement and any future dealings between the parties and/or future publications regarding the parties.
Section 6.8 Force Majeure. Commonwealth shall not incur any liability or penalty for not performing any act or fulfilling any obligation hereunder by reason of any occurrence that is not within its control (including any provision of any present or future law or regulation or any act of any Governmental Authority, any act of God or war or terrorism, or the unavailability, disruption or malfunction of the Internet, the World Wide Web or any other electronic network the Cosmos Network or any aspect thereof, or any consensus attack, or hack, or denial-of-service or other attack, on the Cosmos Network or any aspect thereof, or on the software and infrastructure that enables Commonwealth to operate the Validating NodeInfo.), it being understood that Commonwealth shall use commercially reasonable efforts, consistent with accepted practices in the industries in which Commonwealth operates, as applicable, to resume performance as soon as reasonably practicable under the circumstances.
Section 6.9 Amendments. This Agreement may only be amended, modified, altered or supplemented by Commonwealth. Commonwealth reserves the right to determine the form and means of providing notifications to User, and User agrees to receive legal notices electronically if Commonwealth so chooses. Commonwealth may revise this Agreement from time to time and the most current version of this Agreement will be posted on the Commonwealth website.
Section 6.10 No Waiver. No failure on the part of any Person to exercise any power, right, privilege or remedy under this Agreement, and no delay on the part of any Person in exercising any power, right, privilege or remedy under this Agreement, shall operate as a waiver of such power, right, privilege or remedy; and no single or partial exercise of any such power, right, privilege or remedy shall preclude any other or further exercise thereof or of any other power, right, privilege or remedy. No Person shall be deemed to have waived any claim arising out of this Agreement, or any power, right, privilege or remedy under this Agreement, unless the waiver of such claim, power, right, privilege or remedy is expressly set forth in a written instrument duly executed and delivered on behalf of such Person; and any such waiver shall not be applicable or have any effect except in the specific instance in which it is given.
`;

const TermsPage: m.Component<{}> = {
  oncreate: (vnode) => {
    mixpanel.track('PageVisit', { 'Page Name': 'TermsPage' });
  },
  view: (vnode) => {
    return m('.TermsPage', [
      m('.forum-container', [
        m('h1.page-title', 'Terms of Service'),
        renderMultilineText(TermsOfService),
      ])
    ]);
  }
};

export default TermsPage;
