/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         threadId: 1
 *     }
 */
export interface CreateThreadReactionRequest {
  threadId: number;
  threadMsgId?: string;
  canvasSignedData?: string;
  canvasMsgId?: string;
}
