'use strict';
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, '__esModule', { value: true });
exports.CreateCommentResponseThreadLinksItemSource = void 0;
exports.CreateCommentResponseThreadLinksItemSource = {
  Snapshot: 'snapshot',
  Proposal: 'proposal',
  Thread: 'thread',
  Web: 'web',
  Template: 'template',
};
