'use strict';
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, '__esModule', { value: true });
exports.UpdateCommentResponseThreadAddressUserEmailNotificationInterval =
  void 0;
exports.UpdateCommentResponseThreadAddressUserEmailNotificationInterval = {
  Weekly: 'weekly',
  Never: 'never',
};
