/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';
import { GetGlobalActivityResponseItemThreadDiscordMeta } from './GetGlobalActivityResponseItemThreadDiscordMeta';
import { GetGlobalActivityResponseItemThreadTopic } from './GetGlobalActivityResponseItemThreadTopic';
export declare const GetGlobalActivityResponseItemThread: core.serialization.ObjectSchema<
  serializers.GetGlobalActivityResponseItemThread.Raw,
  CommonApi.GetGlobalActivityResponseItemThread
>;
export declare namespace GetGlobalActivityResponseItemThread {
  interface Raw {
    id: number;
    community_id: string;
    body: string;
    title: string;
    numberOfComments: number;
    created_at?: string | null;
    updated_at?: string | null;
    deleted_at?: string | null;
    locked_at?: string | null;
    kind: string;
    stage: string;
    archived_at?: string | null;
    read_only: boolean;
    has_poll?: boolean | null;
    marked_as_spam_at?: string | null;
    discord_meta?: GetGlobalActivityResponseItemThreadDiscordMeta.Raw | null;
    profile_name?: string | null;
    profile_avatar?: string | null;
    user_id: number;
    user_address: string;
    topic: GetGlobalActivityResponseItemThreadTopic.Raw;
  }
}
