/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';
import { GetGlobalActivityResponseItemRecentCommentsItemDiscordMetaUser } from './GetGlobalActivityResponseItemRecentCommentsItemDiscordMetaUser';
export declare const GetGlobalActivityResponseItemRecentCommentsItemDiscordMeta: core.serialization.ObjectSchema<
  serializers.GetGlobalActivityResponseItemRecentCommentsItemDiscordMeta.Raw,
  CommonApi.GetGlobalActivityResponseItemRecentCommentsItemDiscordMeta
>;
export declare namespace GetGlobalActivityResponseItemRecentCommentsItemDiscordMeta {
  interface Raw {
    user: GetGlobalActivityResponseItemRecentCommentsItemDiscordMetaUser.Raw;
    channel_id: string;
    message_id: string;
  }
}
