/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';
import { GetUserActivityResponseItemDiscordMeta } from './GetUserActivityResponseItemDiscordMeta';
import { GetUserActivityResponseItemRecentCommentsItem } from './GetUserActivityResponseItemRecentCommentsItem';
import { GetUserActivityResponseItemTopic } from './GetUserActivityResponseItemTopic';
export declare const GetUserActivityResponseItem: core.serialization.ObjectSchema<
  serializers.GetUserActivityResponseItem.Raw,
  CommonApi.GetUserActivityResponseItem
>;
export declare namespace GetUserActivityResponseItem {
  interface Raw {
    community_id: string;
    community_icon?: string | null;
    id: number;
    user_id: number;
    user_address: string;
    profile_name?: string | null;
    profile_avatar?: string | null;
    body: string;
    title: string;
    kind: string;
    stage: string;
    number_of_comments: number;
    created_at?: string | null;
    updated_at?: string | null;
    deleted_at?: string | null;
    locked_at?: string | null;
    archived_at?: string | null;
    marked_as_spam_at?: string | null;
    read_only: boolean;
    has_poll?: boolean | null;
    discord_meta?: GetUserActivityResponseItemDiscordMeta.Raw | null;
    topic: GetUserActivityResponseItemTopic.Raw;
    recent_comments?:
      | GetUserActivityResponseItemRecentCommentsItem.Raw[]
      | null;
  }
}
