'use strict';
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding =
  (this && this.__createBinding) ||
  (Object.create
    ? function (o, m, k, k2) {
        if (k2 === undefined) k2 = k;
        var desc = Object.getOwnPropertyDescriptor(m, k);
        if (
          !desc ||
          ('get' in desc ? !m.__esModule : desc.writable || desc.configurable)
        ) {
          desc = {
            enumerable: true,
            get: function () {
              return m[k];
            },
          };
        }
        Object.defineProperty(o, k2, desc);
      }
    : function (o, m, k, k2) {
        if (k2 === undefined) k2 = k;
        o[k2] = m[k];
      });
var __setModuleDefault =
  (this && this.__setModuleDefault) ||
  (Object.create
    ? function (o, v) {
        Object.defineProperty(o, 'default', { enumerable: true, value: v });
      }
    : function (o, v) {
        o['default'] = v;
      });
var __importStar =
  (this && this.__importStar) ||
  function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null)
      for (var k in mod)
        if (k !== 'default' && Object.prototype.hasOwnProperty.call(mod, k))
          __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
  };
Object.defineProperty(exports, '__esModule', { value: true });
exports.CreateThreadResponseReactionsItemAddressUser = void 0;
const core = __importStar(require('../../../../core'));
const CreateThreadResponseReactionsItemAddressUserEmailNotificationInterval_1 = require('./CreateThreadResponseReactionsItemAddressUserEmailNotificationInterval');
const CreateThreadResponseReactionsItemAddressUserProfile_1 = require('./CreateThreadResponseReactionsItemAddressUserProfile');
const CreateThreadResponseReactionsItemAddressUserProfileTagsItem_1 = require('./CreateThreadResponseReactionsItemAddressUserProfileTagsItem');
exports.CreateThreadResponseReactionsItemAddressUser =
  core.serialization.object({
    id: core.serialization.number().optional(),
    email: core.serialization.string().optional(),
    isAdmin: core.serialization.boolean().optional(),
    disableRichText: core.serialization.boolean().optional(),
    emailVerified: core.serialization.boolean().optional(),
    selectedCommunityId: core.serialization.property(
      'selected_community_id',
      core.serialization.string().optional(),
    ),
    emailNotificationInterval:
      CreateThreadResponseReactionsItemAddressUserEmailNotificationInterval_1.CreateThreadResponseReactionsItemAddressUserEmailNotificationInterval.optional(),
    promotionalEmailsEnabled: core.serialization.property(
      'promotional_emails_enabled',
      core.serialization.boolean().optional(),
    ),
    isWelcomeOnboardFlowComplete: core.serialization.property(
      'is_welcome_onboard_flow_complete',
      core.serialization.boolean().optional(),
    ),
    profile:
      CreateThreadResponseReactionsItemAddressUserProfile_1.CreateThreadResponseReactionsItemAddressUserProfile,
    profileTags: core.serialization.property(
      'ProfileTags',
      core.serialization
        .list(
          CreateThreadResponseReactionsItemAddressUserProfileTagsItem_1.CreateThreadResponseReactionsItemAddressUserProfileTagsItem,
        )
        .optional(),
    ),
    createdAt: core.serialization.property(
      'created_at',
      core.serialization.date().optional(),
    ),
    updatedAt: core.serialization.property(
      'updated_at',
      core.serialization.date().optional(),
    ),
  });
