apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
spec:
  size: 3

  image: hashicorp/vault:1.14.8
  bankVaultsImage: ghcr.io/bank-vaults/bank-vaults:latest
  serviceAccount: vault

  existingTlsSecretName: { { .Values.tlsSecretName } }

  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi

  volumeMounts:
    - name: vault-raft
      mountPath: /vault/file

  caNamespaces:
    - '*'

  unsealConfig:
    options:
      preFlightChecks: true
      storeRootToken: true
      secretShares: 5
      secretThreshold: 3
    aws:
      kmsKeyId: { { .Values.kmsKeyArn } }
      region: { { .Values.awsRegion } }

    config:
      storage:
        raft:
          path: /vault/file
      listener:
        tcp:
          address: '0.0.0.0:8200'
          tls_cert_file: /vault/tls/server.crt
          tls_key_file: /vault/tls/server.key
      api_addr: https://vault.default:8200
      cluster_addr: 'https://${HOSTNAME}.vault-internal:8201'
      ui: true

  externalConfig:
    tls:
      disable: false
