/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';
export declare const CreateCommentResponseReactionAddressRole: core.serialization.Schema<
  serializers.CreateCommentResponseReactionAddressRole.Raw,
  CommonApi.CreateCommentResponseReactionAddressRole
>;
export declare namespace CreateCommentResponseReactionAddressRole {
  type Raw = 'admin' | 'moderator' | 'member';
}
