/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from '../../../../core';
export const CreateCommentRequestDiscordMetaUser = core.serialization.object({
  id: core.serialization.string(),
  username: core.serialization.string(),
});
