/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';

export declare const GetCommentsResponseResultsItemReactionAddressRole: core.serialization.Schema<
  serializers.GetCommentsResponseResultsItemReactionAddressRole.Raw,
  CommonApi.GetCommentsResponseResultsItemReactionAddressRole
>;
export declare namespace GetCommentsResponseResultsItemReactionAddressRole {
  type Raw = 'admin' | 'moderator' | 'member';
}
