/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';
import { GetCommentsResponseResultsItemThreadAddressUserApiKey } from './GetCommentsResponseResultsItemThreadAddressUserApiKey';
import { GetCommentsResponseResultsItemThreadAddressUserEmailNotificationInterval } from './GetCommentsResponseResultsItemThreadAddressUserEmailNotificationInterval';
import { GetCommentsResponseResultsItemThreadAddressUserProfile } from './GetCommentsResponseResultsItemThreadAddressUserProfile';
import { GetCommentsResponseResultsItemThreadAddressUserProfileTagsItem } from './GetCommentsResponseResultsItemThreadAddressUserProfileTagsItem';
export declare const GetCommentsResponseResultsItemThreadAddressUser: core.serialization.ObjectSchema<
  serializers.GetCommentsResponseResultsItemThreadAddressUser.Raw,
  CommonApi.GetCommentsResponseResultsItemThreadAddressUser
>;
export declare namespace GetCommentsResponseResultsItemThreadAddressUser {
  interface Raw {
    id?: number | null;
    email?: string | null;
    isAdmin?: boolean | null;
    disableRichText?: boolean | null;
    emailVerified?: boolean | null;
    selected_community_id?: string | null;
    emailNotificationInterval?: GetCommentsResponseResultsItemThreadAddressUserEmailNotificationInterval.Raw | null;
    promotional_emails_enabled?: boolean | null;
    is_welcome_onboard_flow_complete?: boolean | null;
    profile: GetCommentsResponseResultsItemThreadAddressUserProfile.Raw;
    xp_points?: number | null;
    ProfileTags?:
      | GetCommentsResponseResultsItemThreadAddressUserProfileTagsItem.Raw[]
      | null;
    ApiKey?: GetCommentsResponseResultsItemThreadAddressUserApiKey.Raw | null;
    created_at?: string | null;
    updated_at?: string | null;
  }
}
