/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../api/index';
import * as core from '../../../../core';
import * as serializers from '../../../index';
export declare const UpdateCommentResponseThreadSearch: core.serialization.Schema<
  serializers.UpdateCommentResponseThreadSearch.Raw,
  CommonApi.UpdateCommentResponseThreadSearch
>;
export declare namespace UpdateCommentResponseThreadSearch {
  type Raw = string | Record<string, unknown>;
}
