/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type CreateCommentReactionResponseAddressUserEmailNotificationInterval =
  'weekly' | 'never';
export declare const CreateCommentReactionResponseAddressUserEmailNotificationInterval: {
  readonly Weekly: 'weekly';
  readonly Never: 'never';
};
