/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type CreateThreadReactionResponseAddressRole =
  | 'admin'
  | 'moderator'
  | 'member';
export declare const CreateThreadReactionResponseAddressRole: {
  readonly Admin: 'admin';
  readonly Moderator: 'moderator';
  readonly Member: 'member';
};
