import * as Icons from './cw_icons';

export const iconLookup = {
  arrowLeft: Icons.CWArrowLeft,
  arrowRight: Icons.CWArrowRight,
  badge: Icons.CWBadge,
  bell: Icons.CWBell,
  cautionCircle: Icons.CWCautionCircle,
  cautionTriangle: Icons.CWCautionTriangle,
  check: Icons.CWCheck,
  chevronDown: Icons.CWChevronDown,
  chevronLeft: Icons.CWChevronLeft,
  chevronRight: Icons.CWChevronRight,
  close: Icons.CWClose,
  cloud: Icons.CWCloud,
  copy: Icons.CWCopy,
  councilProposal: Icons.CWCouncilProposal,
  cow: Icons.CWCow,
  democraticProposal: Icons.CWDemocraticProposal,
  discord: Icons.CWDiscord,
  dots: Icons.CWDots,
  downvote: Icons.CWDownvote,
  edit: Icons.CWEdit,
  element: Icons.CWElement,
  externalLink: Icons.CWExternalLink,
  feedback: Icons.CWFeedback,
  filter: Icons.CWFilter,
  flag: Icons.CWFlag,
  flame: Icons.CWFlame,
  gear: Icons.CWGear,
  github: Icons.CWGithub,
  hamburger: Icons.CWHamburger,
  heartEmpty: Icons.CWHeartEmpty,
  heartFilled: Icons.CWHeartFilled,
  home: Icons.CWHome,
  infoEmpty: Icons.CWInfoEmpty,
  infoFilled: Icons.CWInfoFilled,
  jar: Icons.CWJar,
  logout: Icons.CWLogout,
  mail: Icons.CWMail,
  people: Icons.CWPeople,
  person: Icons.CWPerson,
  pin: Icons.CWPin,
  plus: Icons.CWPlus,
  plusCircle: Icons.CWPlusCircle,
  search: Icons.CWSearch,
  send: Icons.CWSend,
  share: Icons.CWShare,
  star: Icons.CWStar,
  sun: Icons.CWSun,
  telegram: Icons.CWTelegram,
  trash: Icons.CWTrash,
  treasuryProposal: Icons.CWTreasuryProposal,
  twitter: Icons.CWTwitter,
  upvote: Icons.CWUpvote,
  views: Icons.CWViews,
  wallet: Icons.CWWallet,
  website: Icons.CWWebsite,
};

export type IconName = keyof typeof iconLookup;
