import * as Icons from './cw_icons';

export const iconLookup = {
  add: Icons.CWAdd,
  badge: Icons.CWBadge,
  bell: Icons.CWBell,
  cautionCircle: Icons.CWCautionCircle,
  cautionTriangle: Icons.CWCautionTriangle,
  cow: Icons.CWCow,
  discord: Icons.CWDiscord,
  element: Icons.CWElement,
  externalLink: Icons.CWExternalLink,
  feedback: Icons.CWFeedback,
  filter: Icons.CWFilter,
  flag: Icons.CWFlag,
  flame: Icons.CWFlame,
  gear: Icons.CWGear,
  github: Icons.CWGithub,
  heartEmpty: Icons.CWHeartEmpty,
  heartFilled: Icons.CWHeartFilled,
  logout: Icons.CWLogout,
  pencil: Icons.CWPencil,
  people: Icons.CWPeople,
  person: Icons.CWPerson,
  pin: Icons.CWPin,
  search: Icons.CWSearch,
  send: Icons.CWSend,
  share: Icons.CWShare,
  telegram: Icons.CWTelegram,
  views: Icons.CWViews,
  website: Icons.CWWebsite,
  x: Icons.CWX,
};

export type IconName = keyof typeof iconLookup;
