import * as Icons from './cw_icons';
import * as CustomIcons from './cw_custom_icons';

export const iconLookup = {
  arrowLeft: Icons.CWArrowLeft,
  arrowRight: Icons.CWArrowRight,
  badge: Icons.CWBadge,
  bell: Icons.CWBell,
  cautionCircle: Icons.CWCautionCircle,
  cautionTriangle: Icons.CWCautionTriangle,
  check: Icons.CWCheck,
  chevronDown: Icons.CWChevronDown,
  chevronLeft: Icons.CWChevronLeft,
  chevronRight: Icons.CWChevronRight,
  chevronUp: Icons.CWChevronUp,
  close: Icons.CWClose,
  cloud: Icons.CWCloud,
  collapse: Icons.CWCollapse,
  copy: Icons.CWCopy,
  councilProposal: Icons.CWCouncilProposal,
  cow: Icons.CWCow,
  democraticProposal: Icons.CWDemocraticProposal,
  discord: Icons.CWDiscord,
  dots: Icons.CWDots,
  downvote: Icons.CWDownvote,
  edit: Icons.CWEdit,
  element: Icons.CWElement,
  expand: Icons.CWExpand,
  externalLink: Icons.CWExternalLink,
  feedback: Icons.CWFeedback,
  filter: Icons.CWFilter,
  flag: Icons.CWFlag,
  flame: Icons.CWFlame,
  gear: Icons.CWGear,
  github: Icons.CWGithub,
  hamburger: Icons.CWHamburger,
  hash: Icons.CWHash,
  heartEmpty: Icons.CWHeartEmpty,
  heartFilled: Icons.CWHeartFilled,
  help: Icons.CWHelp,
  home: Icons.CWHome,
  infoEmpty: Icons.CWInfoEmpty,
  infoFilled: Icons.CWInfoFilled,
  jar: Icons.CWJar,
  link: Icons.CWLink,
  lock: Icons.CWLock,
  logout: Icons.CWLogout,
  mail: Icons.CWMail,
  people: Icons.CWPeople,
  person: Icons.CWPerson,
  pin: Icons.CWPin,
  plus: Icons.CWPlus,
  plusCircle: Icons.CWPlusCircle,
  search: Icons.CWSearch,
  send: Icons.CWSend,
  share: Icons.CWShare,
  share2: Icons.CWShare2,
  star: Icons.CWStar,
  sun: Icons.CWSun,
  telegram: Icons.CWTelegram,
  trash: Icons.CWTrash,
  treasuryProposal: Icons.CWTreasuryProposal,
  twitter: Icons.CWTwitter,
  upvote: Icons.CWUpvote,
  views: Icons.CWViews,
  wallet: Icons.CWWallet,
  website: Icons.CWWebsite,
};

export const customIconLookup = {
  'cosm-metamask': CustomIcons.CWCosmosEvmMetamask,
  keplr: CustomIcons.CWKeplr,
  // magic: CustomIcons.CWMagic, // weird xlinkhref, should be 32
  metamask: CustomIcons.CWMetaMask,
  near: CustomIcons.CWNearWallet,
  // phantom: CustomIcons.CWPhantom, // weird xlinkhref
  polkadot: CustomIcons.CWPolkadot,
  // ronin: CustomIcons.CWRonin, // weird xlinkhref
  terrastation: CustomIcons.CWTerraStation,
  walletconnect: CustomIcons.CWWalletConnect,
};

export type IconName = keyof typeof iconLookup;
export type CustomIconName = keyof typeof customIconLookup;
