/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../index';
export interface CreateCommentResponseAddress {
  id?: number;
  address: string;
  communityId: string;
  userId?: number;
  verificationToken?: string;
  verificationTokenExpires?: Date;
  verified?: Date;
  lastActive?: Date;
  ghostAddress?: boolean;
  walletId?: CommonApi.CreateCommentResponseAddressWalletId;
  blockInfo?: string;
  isUserDefault?: boolean;
  role?: CommonApi.CreateCommentResponseAddressRole;
  isBanned?: boolean;
  hex?: string;
  user?: CommonApi.CreateCommentResponseAddressUser;
  createdAt?: Date;
  updatedAt?: Date;
}
