/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface CreateCommentResponseReactionAddressUserApiKey {
  userId?: number;
  hashedApiKey: string;
  salt: string;
  createdAt?: Date;
  updatedAt?: Date;
}
