/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface CreateCommentResponseCommentVersionHistoriesItem {
  id?: number;
  commentId: number;
  text: string;
  timestamp: Date;
  contentUrl?: string;
}
