/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from "../../../index";
export interface CreateCommentResponseThreadDiscordMeta {
    user: CommonApi.CreateCommentResponseThreadDiscordMetaUser;
    channelId: string;
    messageId: string;
}
