/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../index';

export interface CreateCommentResponseAddressUser {
  id?: number;
  email?: string;
  isAdmin?: boolean;
  disableRichText?: boolean;
  emailVerified?: boolean;
  selectedCommunityId?: string;
  emailNotificationInterval?: CommonApi.CreateCommentResponseAddressUserEmailNotificationInterval;
  promotionalEmailsEnabled?: boolean;
  isWelcomeOnboardFlowComplete?: boolean;
  profile: CommonApi.CreateCommentResponseAddressUserProfile;
  profileTags?: CommonApi.CreateCommentResponseAddressUserProfileTagsItem[];
  createdAt?: Date;
  updatedAt?: Date;
}
