/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface GetCommentsResponseResultsItemAddressUserProfileTagsItem {
  userId: number;
  tagId: number;
  createdAt?: Date;
  updatedAt?: Date;
}
