/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from "../../../index";
export interface GetCommentsResponseResultsItemDiscordMeta {
    user: CommonApi.GetCommentsResponseResultsItemDiscordMetaUser;
    channelId: string;
    messageId: string;
}
