/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from "../../../index";
export interface GetCommentsResponseResultsItemReactionAddressUser {
    id?: number;
    email?: string;
    isAdmin?: boolean;
    disableRichText?: boolean;
    emailVerified?: boolean;
    selectedCommunityId?: string;
    emailNotificationInterval?: CommonApi.GetCommentsResponseResultsItemReactionAddressUserEmailNotificationInterval;
    promotionalEmailsEnabled?: boolean;
    isWelcomeOnboardFlowComplete?: boolean;
    profile: CommonApi.GetCommentsResponseResultsItemReactionAddressUserProfile;
    profileTags?: CommonApi.GetCommentsResponseResultsItemReactionAddressUserProfileTagsItem[];
    createdAt?: Date;
    updatedAt?: Date;
}
