/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type UpdateCommentResponseThreadAddressRole = "admin" | "moderator" | "member";
export declare const UpdateCommentResponseThreadAddressRole: {
    readonly Admin: "admin";
    readonly Moderator: "moderator";
    readonly Member: "member";
};
