apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  destination:
    namespace: cloudflare
    server: https://kubernetes.default.svc
  source:
    path: charts/cloudflare-tunnel-remote
    repoURL: https://github.com/cloudflare/helm-charts.git
    targetRevision: main
    helm:
      parameters:
        - name: fullnameOverride
          value: cloudflare-tunnel
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
