/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as CommonApi from '../../../../../api/index';
import * as core from '../../../../../core';
import * as serializers from '../../../../index';
import { CreateTopicRequestWeightedVoting } from '../../types/CreateTopicRequestWeightedVoting';

export declare const CreateTopicRequest: core.serialization.Schema<
  serializers.CreateTopicRequest.Raw,
  CommonApi.CreateTopicRequest
>;
export declare namespace CreateTopicRequest {
  interface Raw {
    community_id: string;
    name?: string | null;
    description?: string | null;
    featured_in_sidebar?: boolean | null;
    featured_in_new_post?: boolean | null;
    default_offchain_template?: string | null;
    weighted_voting?: CreateTopicRequestWeightedVoting.Raw | null;
    chain_node_id?: number | null;
    token_address?: string | null;
    token_symbol?: string | null;
    vote_weight_multiplier?: number | null;
  }
}
