apiVersion: v1
kind: Service
metadata:
  name: commonwealth-server{{ .Values.commonwealthServerSuffix }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: commonwealth-server{{ .Values.commonwealthServerSuffix }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080