import {
  ArrowBendUpRightIcon,
  ArrowClockwiseIcon,
  ArrowFatDownIcon,
  ArrowFatUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowsClockwiseIcon,
  ArrowsInSimpleIcon,
  ArrowsOutSimpleIcon,
  Barcode,
  BellSimpleIcon,
  BellSimpleRingingIcon,
  BellSimpleSlashIcon,
  BinocularsIcon,
  BookOpenTextIcon,
  BrainIcon,
  CalendarBlankIcon,
  CardholderIcon,
  CaretDoubleLeftIcon,
  CaretDoubleRightIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  ChartLineUpIcon,
  ChatCenteredDotsIcon,
  ChatDotsIcon,
  ChatTextIcon,
  ChatsIcon,
  CheckCircleIcon,
  CheckIcon,
  CircleNotchIcon,
  CirclesFourIcon,
  CirclesThreePlusIcon,
  ClipboardIcon,
  ClockCounterClockwiseIcon,
  CloudArrowUpIcon,
  CodeIcon,
  CoinsIcon,
  CompassIcon,
  CopyIcon,
  CopySimpleIcon,
  DiscordLogoIcon,
  DotsThreeVerticalIcon,
  DownloadIcon,
  DownloadSimpleIcon,
  ExportIcon,
  EyeIcon,
  FlagIcon,
  FunnelSimpleIcon,
  GavelIcon,
  GearIcon,
  HeartIcon,
  HouseIcon,
  HouseSimpleIcon,
  ImageIcon,
  ImageSquareIcon,
  KanbanIcon,
  LightbulbIcon,
  LinkBreakIcon,
  LinkIcon,
  ListChecksIcon,
  ListDashesIcon,
  ListNumbersIcon,
  LockIcon,
  LockKeyIcon,
  LockKeyOpenIcon,
  LockOpenIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  NotchesIcon,
  NotePencilIcon,
  NotepadIcon,
  PaperPlaneTiltIcon,
  PencilSimpleIcon,
  PlayIcon,
  PlusCircleIcon,
  PlusIcon,
  PushPinIcon,
  QuestionIcon,
  QuotesIcon,
  RocketLaunchIcon,
  RowsIcon,
  SignOutIcon,
  SparkleIcon,
  SquaresFourIcon,
  StarFourIcon,
  TableIcon,
  TextBIcon,
  TextHOneIcon,
  TextHThreeIcon,
  TextHTwoIcon,
  TextItalicIcon,
  TextStrikethroughIcon,
  TextSubscriptIcon,
  TextSuperscriptIcon,
  TextUnderlineIcon,
  TimerIcon,
  TrashIcon,
  TrayArrowDownIcon,
  TriangleIcon,
  TrophyIcon,
  TwitterLogoIcon,
  UserSwitchIcon,
  UsersIcon,
  UsersThreeIcon,
  WarningIcon,
  XLogoIcon,
} from '@phosphor-icons/react';
import * as CustomIcons from './cw_custom_icons';
import { CWPara } from './cw_custom_icons';
import * as Icons from './cw_icons';
import { withPhosphorIcon } from './cw_phosphor_icons';

export const iconLookup = {
  bold: withPhosphorIcon(TextBIcon),
  brain: withPhosphorIcon(BrainIcon),
  italic: withPhosphorIcon(TextItalicIcon),
  underline: withPhosphorIcon(TextUnderlineIcon),
  strikethrough: withPhosphorIcon(TextStrikethroughIcon),
  superscript: withPhosphorIcon(TextSuperscriptIcon),
  subscript: withPhosphorIcon(TextSubscriptIcon),
  listDashes: withPhosphorIcon(ListDashesIcon),
  listNumbers: withPhosphorIcon(ListNumbersIcon),
  listChecks: withPhosphorIcon(ListChecksIcon),
  h1: withPhosphorIcon(TextHOneIcon),
  h2: withPhosphorIcon(TextHTwoIcon),
  h3: withPhosphorIcon(TextHThreeIcon),
  q: withPhosphorIcon(QuotesIcon),
  p: CWPara,
  quote: withPhosphorIcon(QuotesIcon),
  quotes: withPhosphorIcon(QuotesIcon),
  table: withPhosphorIcon(TableIcon),
  image: withPhosphorIcon(ImageIcon),
  clipboard: withPhosphorIcon(ClipboardIcon),
  cloudArrowUp: withPhosphorIcon(CloudArrowUpIcon),
  element: Icons.CWElement,
  archiveTrayFilled: Icons.CWArchiveTrayFilled,
  arrowDownBlue500: Icons.CWArrowDownBlue500,
  arrowFatUp: Icons.CWArrowFatUp,
  arrowFatUpNeutral: Icons.CWArrowFatUpNeutral,
  arrowUpHalfGreen: Icons.CWArrowUpHalfGreen,
  arrowDownHalfOrange: Icons.CWArrowDownHalfOrange,
  arrowFatUpBlue500: Icons.CWArrowFatUpBlue500,
  arrowsClockwise: withPhosphorIcon(ArrowsClockwiseIcon),
  arrowClockwise: withPhosphorIcon(ArrowClockwiseIcon),
  arrowFatUpBlue600: Icons.CWArrowFatUpBlue600,
  arrowUpBlue500: Icons.CWArrowUpBlue500,
  arrowUpNeutral400: Icons.CWArrowUpNeutral400,
  arrowSquareOut: withPhosphorIcon(ArrowSquareOutIcon),
  arrowsInSimple: withPhosphorIcon(ArrowsInSimpleIcon),
  arrowsOutSimple: withPhosphorIcon(ArrowsOutSimpleIcon),
  keyLockOpened: withPhosphorIcon(LockKeyOpenIcon),
  keyLockClosed: withPhosphorIcon(LockKeyIcon),
  eye: withPhosphorIcon(EyeIcon),
  export: withPhosphorIcon(ExportIcon),
  archiveTray: withPhosphorIcon(TrayArrowDownIcon),
  arrowLeft: Icons.CWArrowLeft,
  arrowRight: Icons.CWArrowRight,
  arrowRightPhosphor: withPhosphorIcon(ArrowRightIcon),
  arrowLeftPhosphor: withPhosphorIcon(ArrowLeftIcon),
  backer: Icons.CWBacker,
  barcode: withPhosphorIcon(Barcode),
  badge: Icons.CWBadge,
  bell: withPhosphorIcon(BellSimpleIcon),
  bellNew: Icons.CWBellNew,
  bellRinging: withPhosphorIcon(BellSimpleRingingIcon),
  bellMuted: withPhosphorIcon(BellSimpleSlashIcon),
  bookOpenText: withPhosphorIcon(BookOpenTextIcon),
  calenderBlank: withPhosphorIcon(CalendarBlankIcon),
  cardholder: withPhosphorIcon(CardholderIcon),
  cautionCircle: Icons.CWCautionCircle,
  cautionTriangle: Icons.CWCautionTriangle,
  chatDots: withPhosphorIcon(ChatDotsIcon),
  check: Icons.CWCheck,
  checkNew: withPhosphorIcon(CheckIcon),
  checkCircle: withPhosphorIcon(CheckCircleIcon),
  checkCircleFilled: (props) =>
    withPhosphorIcon(CheckCircleIcon)({ weight: 'fill', ...props }),
  chevronDown: Icons.CWChevronDown,
  chevronLeft: Icons.CWChevronLeft,
  chevronRight: Icons.CWChevronRight,
  chevronUp: Icons.CWChevronUp,
  chats: withPhosphorIcon(ChatsIcon),
  circlesThreeplus: withPhosphorIcon(CirclesThreePlusIcon),
  circleNotch: withPhosphorIcon(CircleNotchIcon),
  caretUp: withPhosphorIcon(CaretUpIcon),
  caretDown: withPhosphorIcon(CaretDownIcon),
  caretLeft: withPhosphorIcon(CaretLeftIcon),
  caretRight: withPhosphorIcon(CaretRightIcon),
  caretDoubleRight: withPhosphorIcon(CaretDoubleRightIcon),
  caretDoubleLeft: withPhosphorIcon(CaretDoubleLeftIcon),
  clock: Icons.CWClock,
  close: Icons.CWClose,
  cloud: Icons.CWCloud,
  chartLineUp: withPhosphorIcon(ChartLineUpIcon),
  code: withPhosphorIcon(CodeIcon),
  coins: withPhosphorIcon(CoinsIcon),
  collapse: Icons.CWCollapse,
  commonLogo: Icons.CWCommonLogo,
  comment: withPhosphorIcon(ChatCenteredDotsIcon),
  compass: Icons.CWCompass,
  compassPhosphor: withPhosphorIcon(CompassIcon),
  copy: Icons.CWCopy,
  copyNew: withPhosphorIcon(CopyIcon),
  clockCounterClockwise: withPhosphorIcon(ClockCounterClockwiseIcon),
  cosmos: Icons.CWCosmos,
  cow: Icons.CWCow,
  curator: Icons.CWCurator,
  delegate: Icons.CWDelegate,
  democraticProposal: Icons.CWDemocraticProposal,
  discord: Icons.CWDiscord,
  discordOld: Icons.CWDiscordLogin, // TODO: possible remove
  dot: Icons.CWDot,
  dots: Icons.CWDots,
  dotsVertical: Icons.CWDotsVertical,
  dotsThreeVertical: withPhosphorIcon(DotsThreeVerticalIcon),
  dotsHorizontal: Icons.CWDotsHorizontal,
  downvote: withPhosphorIcon(ArrowFatDownIcon),
  edgeware: Icons.CWEdgeware,
  envelope: Icons.CWEnvelope,
  ethereum: Icons.CWEthereum,
  etherscan: Icons.CWEtherscan,
  expand: Icons.CWExpand,
  exploreCommunity: Icons.CWExploreCommunities,
  externalLink: Icons.CWExternalLink,
  feedback: Icons.CWFeedback,
  filter: Icons.CWFilter,
  // flag: Icons.CWFlag,
  flag: withPhosphorIcon(FlagIcon),
  funnelSimple: withPhosphorIcon(FunnelSimpleIcon),
  flame: Icons.CWFlame,
  gear: Icons.CWGear,
  gearPhosphor: withPhosphorIcon(GearIcon),
  github: Icons.CWGithub,
  octocat: Icons.CWOctocat,
  google: Icons.CWGoogle,
  gavel: withPhosphorIcon(GavelIcon),
  hamburger: Icons.CWHamburger,
  hash: Icons.CWHash,
  heart: withPhosphorIcon(HeartIcon),
  heartEmpty: Icons.CWHeartEmpty,
  heartFilled: Icons.CWHeartFilled,
  help: Icons.CWHelp,
  home: Icons.CWHome,
  house: withPhosphorIcon(HouseIcon),
  houseSimple: withPhosphorIcon(HouseSimpleIcon),
  imageUpload: Icons.CWImageUpload,
  infoEmpty: Icons.CWInfoEmpty,
  infoFilled: Icons.CWInfoFilled,
  imageSquare: withPhosphorIcon(ImageSquareIcon),
  jar: Icons.CWJar,
  link: Icons.CWLink,
  lightbulb: withPhosphorIcon(LightbulbIcon),
  linkPhosphor: withPhosphorIcon(LinkIcon),
  linkBreak: withPhosphorIcon(LinkBreakIcon),
  lock: Icons.CWLock,
  lockedNew: withPhosphorIcon(LockIcon),
  lockOpenNew: withPhosphorIcon(LockOpenIcon),
  logout: Icons.CWLogout,
  mail: Icons.CWMail,
  magnifyingGlass: withPhosphorIcon(MagnifyingGlassIcon),
  minus: withPhosphorIcon(MinusIcon),
  mute: Icons.CWMute,
  near: Icons.CWNear,
  newStar: Icons.CWNewStar,
  notches: withPhosphorIcon(NotchesIcon),
  notePencil: withPhosphorIcon(NotePencilIcon),
  notepad: withPhosphorIcon(NotepadIcon),
  paperPlaneTilt: withPhosphorIcon(PaperPlaneTiltIcon),
  people: Icons.CWPeople,
  peopleNew: withPhosphorIcon(UsersThreeIcon),
  person: Icons.CWPerson,
  pencil: withPhosphorIcon(PencilSimpleIcon),
  // pin: Icons.CWPin,
  pin: withPhosphorIcon(PushPinIcon),
  plus: Icons.CWPlus,
  plusPhosphor: withPhosphorIcon(PlusIcon),
  plusCircle: Icons.CWPlusCircle,
  plusCirclePhosphor: (props) => withPhosphorIcon(PlusCircleIcon)(props),
  polkadot: Icons.CWPolkadot,
  polygon: Icons.CWPolygon,
  rows: (props) => withPhosphorIcon(RowsIcon)(props),
  rocketLaunch: (props) => withPhosphorIcon(RocketLaunchIcon)(props),
  question: withPhosphorIcon(QuestionIcon),
  search: Icons.CWSearch,
  send: Icons.CWSend,
  // share: Icons.CWShare,
  share: withPhosphorIcon(ArrowBendUpRightIcon),
  share2: Icons.CWShare2,
  sidebarCollapse: Icons.CWSidebarCollapse,
  sidebarExpand: Icons.CWSidebarExpand,
  signOut: withPhosphorIcon(SignOutIcon),
  sparkle: withPhosphorIcon(SparkleIcon),
  squaresFour: (props) => withPhosphorIcon(SquaresFourIcon)(props),
  star: Icons.CWStar,
  sun: Icons.CWSun,
  telegram: Icons.CWTelegram,
  tiktok: Icons.CWTiktok,
  trophy: withPhosphorIcon(TrophyIcon),
  timer: withPhosphorIcon(TimerIcon),
  transfer: Icons.CWTransfer,
  triangle: withPhosphorIcon(TriangleIcon),
  // trash: Icons.CWTrash,
  trash: withPhosphorIcon(TrashIcon),
  treasuryProposal: Icons.CWTreasuryProposal,
  trendUp: Icons.CWTrendUp,
  twitter: Icons.CWTwitter,
  twitterNew: Icons.CWTwitterNew,
  twitterOutline: withPhosphorIcon(TwitterLogoIcon),
  twitterX: Icons.CWTwitterX,
  unsubscribe: Icons.CWUnsubscribe,
  upvote: withPhosphorIcon(ArrowFatUpIcon),
  users: withPhosphorIcon(UsersIcon),
  userSwitch: withPhosphorIcon(UserSwitchIcon),
  vote: Icons.CWVote,
  views: Icons.CWViews,
  wallet: Icons.CWWallet,
  warning: (props) => withPhosphorIcon(WarningIcon)(props),
  website: Icons.CWWebsite,
  write: Icons.CWWrite,
  members: Icons.CWMembers,
  download: withPhosphorIcon(DownloadIcon),
  downloadSimple: withPhosphorIcon(DownloadSimpleIcon),
  copySimple: withPhosphorIcon(CopySimpleIcon),
  viewAll: withPhosphorIcon(RowsIcon),
  viewOverView: withPhosphorIcon(CirclesFourIcon),
  kanban: withPhosphorIcon(KanbanIcon),
  xTwitter: withPhosphorIcon(XLogoIcon),
  discordLogo: withPhosphorIcon(DiscordLogoIcon),
  warpcast: Icons.CWWarpcast,
  play: withPhosphorIcon(PlayIcon),
  starFour: withPhosphorIcon(StarFourIcon),
  // Chain icons with distinct names
  solanaChain: CustomIcons.CWSolana,
  nearChain: CustomIcons.CWNearIcon,
  ethChain: CustomIcons.CWEth,
  cosmosChain: CustomIcons.CWCosmos,
  polkadotChain: CustomIcons.CWPolkadot,
  globe: Icons.CWGlobe,
  whiteCheck: Icons.CWWhiteCheck,
  pins: Icons.CWPin,
  starGolden: Icons.CWStarGolden,
  socialVerified: Icons.CWSocialVerified,
  sandClock: Icons.CWSandClock,
  stopSymbol: Icons.CWStopSymbol,
  binoculars: withPhosphorIcon(BinocularsIcon),
};

export const customIconLookup = {
  base: CustomIcons.CWBase,
  blast: CustomIcons.CWBlast,
  binance: CustomIcons.CWBinance,
  google: Icons.CWGoogle,
  github: Icons.CWGithub,
  email: CustomIcons.CWEmail,
  solana: CustomIcons.CWSolana,
  nearIcon: CustomIcons.CWNearIcon,
  eth: CustomIcons.CWEth,
  cosmos: CustomIcons.CWCosmos,
  polkadot: CustomIcons.CWPolkadot,
  discordIcon: CustomIcons.CWDiscord,
  octocat: Icons.CWOctocat,
  hamburger: Icons.CWHamburger,
  keplr: CustomIcons.CWKeplr,
  leap: CustomIcons.CWLeap,
  magic: CustomIcons.CWMagic,
  metamask: CustomIcons.CWMetaMask,
  moonpay: CustomIcons.CWMoonPay,
  near: CustomIcons.CWNearWallet,
  phantom: CustomIcons.CWPhantom,
  backpack: CustomIcons.CWBackpack,
  solflare: CustomIcons.CWSolflare,
  sui: CustomIcons.CWSui,
  'sui-wallet': CustomIcons.CWSui,
  suiet: CustomIcons.CWSuiet,
  bitget: CustomIcons.CWBitget,
  'okx-wallet': CustomIcons.CWOKX,
  'suiet-wallet': CustomIcons.CWSuiet,
  terrastation: CustomIcons.CWTerraStation2,
  unreads: CustomIcons.CWUnreads,
  walletconnect: CustomIcons.CWWalletConnect,
  'terra-walletconnect': CustomIcons.CWWalletConnect,
  coinbase: CustomIcons.CWCoinbase,
  x: CustomIcons.CWX, // twitter
  apple: CustomIcons.CWApple,
  farcaster: CustomIcons.CWFarcaster,
  SMS: withPhosphorIcon(ChatTextIcon),
  privy: CustomIcons.CWPrivy,
  okx: CustomIcons.CWOKX,
  twitterIcon: CustomIcons.CWTwitter,
  envelope: CustomIcons.CWEnvelop,
  'keplr-ethereum': CustomIcons.CWKeplr,
  'cosm-metamask': CustomIcons.CWMetaMask,
};

export type IconName = keyof typeof iconLookup;
export type CustomIconName = keyof typeof customIconLookup;
