export const communityNominationsAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_namespaceFactory', type: 'address', internalType: 'address' },
      { name: '_feeDestination', type: 'address', internalType: 'address' },
      { name: '_feeAmount', type: 'uint256', internalType: 'uint256' },
      { name: '_owner', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'configureCommunitNominations',
    inputs: [
      { name: 'namespace', type: 'string', internalType: 'string' },
      { name: '_referralModeEnabled', type: 'bool', internalType: 'bool' },
      { name: '_maxNominations', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'feeAmount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'feeDestination',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxNominations',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'namespaceFactory',
    inputs: [],
    outputs: [
      { name: '', type: 'address', internalType: 'contract INamespaceFactory' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'newOwner',
    inputs: [{ name: '_newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'nominateJudges',
    inputs: [
      { name: 'namespace', type: 'string', internalType: 'string' },
      { name: 'judges', type: 'address[]', internalType: 'address[]' },
      { name: 'judgeId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'nominationCount',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nominatorOf',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'referralModeEnabled',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setFeeAmount',
    inputs: [{ name: '_feeAmount', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setFeeDestination',
    inputs: [
      { name: '_feeDestination', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'JudgeNominated',
    inputs: [
      {
        name: 'namespace',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
      {
        name: 'judge',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'judgeId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'nominator',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'currentNominations',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NominationsConfigured',
    inputs: [
      {
        name: 'namespace',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
      {
        name: 'referralModeEnabled',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: 'maxNominations',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
] as const;
