export const namespaceFactoryAbi = [
  {
    type: 'function',
    name: 'CurveManager',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'communityNominations',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract ICommunityNominations',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'communityStake',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'configureCommunityStakeId',
    inputs: [
      { name: 'name', type: 'string', internalType: 'string' },
      { name: 'tokenName', type: 'string', internalType: 'string' },
      { name: 'id', type: 'uint256', internalType: 'uint256' },
      { name: 'exchangeToken', type: 'address', internalType: 'address' },
      { name: 'scalar', type: 'uint256', internalType: 'uint256' },
      { name: 'curve', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'configureNominationStrategy',
    inputs: [
      { name: 'name', type: 'string', internalType: 'string' },
      { name: 'maxNominations', type: 'uint256', internalType: 'uint256' },
      { name: 'referralModeEnabled', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'contestFactoryUtil',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IContestFactoryUtils',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'deployNamespace',
    inputs: [
      { name: 'name', type: 'string', internalType: 'string' },
      { name: '_uri', type: 'string', internalType: 'string' },
      { name: '_feeManager', type: 'address', internalType: 'address' },
      { name: '_signature', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'deployNamespaceWithReferrer',
    inputs: [
      { name: 'name', type: 'string', internalType: 'string' },
      { name: '_uri', type: 'string', internalType: 'string' },
      { name: '_feeManager', type: 'address', internalType: 'address' },
      { name: 'referrer', type: 'address', internalType: 'address' },
      { name: '_signature', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'erc20VoteStrategy',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IERC20VoteStrategy',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getNamespace',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      { name: '_communityStake', type: 'address', internalType: 'address' },
      { name: '_namespaceLogic', type: 'address', internalType: 'address' },
      { name: '_reservationHook', type: 'address', internalType: 'address' },
      { name: '_curveManager', type: 'address', internalType: 'address' },
      {
        name: '_namespaceVotingStrategy',
        type: 'address',
        internalType: 'address',
      },
      { name: '_contestFactoryUtil', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'namespaceLogic',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'namespaceVotingStrategy',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract INamespaceVoteStrategy',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'newContest',
    inputs: [
      { name: 'name', type: 'string', internalType: 'string' },
      { name: 'interval', type: 'uint256', internalType: 'uint256' },
      { name: 'winnerShares', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'id', type: 'uint256', internalType: 'uint256' },
      { name: 'prizeShare', type: 'uint256', internalType: 'uint256' },
      { name: 'voterShare', type: 'uint256', internalType: 'uint256' },
      { name: 'feeShare', type: 'uint256', internalType: 'uint256' },
      { name: 'weight', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'newSingleContest',
    inputs: [
      { name: 'name', type: 'string', internalType: 'string' },
      { name: 'length', type: 'uint256', internalType: 'uint256' },
      { name: 'winnerShares', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'id', type: 'uint256', internalType: 'uint256' },
      { name: 'voterShare', type: 'uint256', internalType: 'uint256' },
      { name: 'weight', type: 'uint256', internalType: 'uint256' },
      { name: 'exhangeToken', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'newSingleERC20Contest',
    inputs: [
      { name: 'name', type: 'string', internalType: 'string' },
      { name: 'length', type: 'uint256', internalType: 'uint256' },
      { name: 'winnerShares', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'voterShare', type: 'uint256', internalType: 'uint256' },
      { name: 'exhangeToken', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'newSingleJudgedContest',
    inputs: [
      { name: 'name', type: 'string', internalType: 'string' },
      { name: 'length', type: 'uint256', internalType: 'uint256' },
      { name: 'winnerShares', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'voterShare', type: 'uint256', internalType: 'uint256' },
      { name: 'exhangeToken', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'onERC1155BatchReceived',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256[]', internalType: 'uint256[]' },
      { name: '', type: 'uint256[]', internalType: 'uint256[]' },
      { name: '', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [{ name: '', type: 'bytes4', internalType: 'bytes4' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'onERC1155Received',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [{ name: '', type: 'bytes4', internalType: 'bytes4' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'referralFeeManager',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IReferralFeeManager',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'reinitialize',
    inputs: [
      { name: '_erc20VoteStrategy', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'reservationHook',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setReservationHook',
    inputs: [{ name: '_hook', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateContestUtilImplementation',
    inputs: [{ name: 'newUtil', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateNamespaceImplementation',
    inputs: [
      { name: 'newImplementation', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateReferralManager',
    inputs: [
      {
        name: '_referralManager',
        type: 'address',
        internalType: 'address payable',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'ConfiguredCommunityStakeId',
    inputs: [
      { name: 'name', type: 'string', indexed: false, internalType: 'string' },
      {
        name: 'tokenName',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
      { name: 'id', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DeployedNamespace',
    inputs: [
      {
        name: 'nameSpace',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: '_feeManager',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: '_signature',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
      {
        name: '_namespaceDeployer',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DeployedNamespaceWithReferral',
    inputs: [
      {
        name: 'nameSpace',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'feeManager',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'referrer',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'referralFeeManager',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'signature',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
      {
        name: 'namespaceDeployer',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [
      {
        name: 'version',
        type: 'uint64',
        indexed: false,
        internalType: 'uint64',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NewContest',
    inputs: [
      {
        name: 'contest',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'namespace',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'interval',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      { name: 'oneOff', type: 'bool', indexed: false, internalType: 'bool' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'InvalidInitialization', inputs: [] },
  { type: 'error', name: 'NotInitializing', inputs: [] },
] as const;
