export const recurringContestAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: 'initParams',
        type: 'tuple',
        internalType: 'struct ContestGovernor.InitializationParams',
        components: [
          { name: '_startTime', type: 'uint256', internalType: 'uint256' },
          {
            name: '_contestInterval',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: '_votingStrategy', type: 'address', internalType: 'address' },
          {
            name: '_claimHookAddress',
            type: 'address',
            internalType: 'address',
          },
          {
            name: '_contentHookAddress',
            type: 'address',
            internalType: 'address',
          },
          {
            name: '_winnerShares',
            type: 'uint256[]',
            internalType: 'uint256[]',
          },
          { name: '_contestToken', type: 'address', internalType: 'address' },
          {
            name: '_prizeShare',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: '_voterShare', type: 'uint256', internalType: 'uint256' },
          {
            name: '_namespace',
            type: 'address',
            internalType: 'address',
          },
          {
            name: '_protocolFeePercentage',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: '_protocolFeeDestination',
            type: 'address',
            internalType: 'address',
          },
        ],
      },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    name: 'FeeMangerAddress',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'addContent',
    inputs: [
      { name: 'creator', type: 'address', internalType: 'address' },
      {
        name: 'url',
        type: 'string',
        internalType: 'string',
      },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimHook',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IContestGovernorClaimHook',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'claimVoterRewards',
    inputs: [{ name: 'voter', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'completedContests',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'claimed', type: 'bool', internalType: 'bool' },
      {
        name: 'totalPrize',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'content',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'url', type: 'string', internalType: 'string' },
      {
        name: 'cumulativeVotes',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'creator', type: 'address', internalType: 'address' },
      {
        name: 'isWinner',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'contentHook',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IContestGovernorContentHook',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'contestId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'contestInterval',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'contestToken',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'currMinWinVotes',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'currentContentId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'deposit',
    inputs: [{ name: 'amount', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'endTime',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPastWinners',
    inputs: [{ name: 'contestId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getWinnerIds',
    inputs: [],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'namespace',
    inputs: [],
    outputs: [
      { name: '', type: 'address', internalType: 'contract INamespace' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'newContest',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'nextPrizeShare',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'prizeShare',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'protocolFeeDestination',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'protocolFeePercentage',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'startTime',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'updatePrizeShare',
    inputs: [{ name: 'newShare', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'voteContent',
    inputs: [
      { name: 'voter', type: 'address', internalType: 'address' },
      {
        name: 'id',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'voterShare',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'votingStrategy',
    inputs: [],
    outputs: [
      { name: '', type: 'address', internalType: 'contract IVotingStrategy' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'winnerIds',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'ContentAdded',
    inputs: [
      {
        name: 'contentId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'creator',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'url',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NewRecurringContestStarted',
    inputs: [
      {
        name: 'contestId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'startTime',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endTime',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PrizeShareUpdated',
    inputs: [
      {
        name: 'newPrizeShare',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TransferFailed',
    inputs: [
      {
        name: 'token',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'to',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'VoterVoted',
    inputs: [
      {
        name: 'voter',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'contentId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'contestId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'votingPower',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
] as const;
