name: Build Docker Image

on:
  push:
    branches:
      - staging
      - frick
      - frack

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Heroku app name based on branch
        id: set-heroku-app-name
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          case $BRANCH_NAME in
            frick)
              APP_NAME="commonwealth-frick"
              ;;
            frack)
              APP_NAME="commonwealth-frack"
              ;;
            staging)
              APP_NAME="commonwealth-beta"
              ;;
            demo)
              APP_NAME="commonwealth-demo"
              ;;
            *)
              echo "Branch $BRANCH_NAME is not configured for deployment."
              exit 1
              ;;
          esac
          echo "HEROKU_APP_NAME=$APP_NAME" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          dontautocreate: true
          docker_heroku_process_type: web, consumer, evm-ce, knock, message-relayer