name: Build Docker Image

on:
  push:
    branches:
      - frick
      - frack
      - beta
      - production
      - master

  workflow_run:
    workflows:
      - "Pre-Release Notes & Merge"  # Match the name in `cut_release.yml`
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Heroku app name based on branch
        id: set-heroku-app-name
        run: |
          if [ "${{ github.event_name }}" == "workflow_run" ]; then
            BRANCH_NAME="beta" 
          else
            BRANCH_NAME=${GITHUB_REF##*/}
          fi
          
          case $BRANCH_NAME in
            frick)
              APP_NAME="commonwealth-frick"
              ;;
            frack)
              APP_NAME="commonwealth-frack"
              ;;
            beta)
              APP_NAME="commonwealth-beta"
              ;;
            master)
              APP_NAME="commonwealth-demo"
              ;;
            production)
              APP_NAME="commonwealthapp"
              ;;
            *)
              echo "Branch $BRANCH_NAME is not configured for deployment."
              exit 1
              ;;
          esac
          echo "HEROKU_APP_NAME=$APP_NAME" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        run: |
          chmod +x ./scripts/deploy-to-heroku.sh
          ./scripts/deploy-to-heroku.sh "${{ secrets.HEROKU_EMAIL }}" "${{ secrets.HEROKU_API_TOKEN }}" "${{ env.HEROKU_APP_NAME }}"