# Workflow name
name: 'Chromatic'

# Event for the workflow
on:
  pull_request:
    types: [labeled]

# List of jobs
jobs:
  chromatic-deployment:
    if: ${{ github.event.label.name == 'Design System Update' }}
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. pnpm, npm, pnpm
        run: pnpm
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish commonwealth package to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/commonwealth
